# CCP Literacy Estimation — Step-by-Step Demo (Model 1)

This notebook shows CCP estimation, transitions, CCS, a small MD fit, and a light EM loop.

In [24]:
import numpy as np, pandas as pd, json
from collections import defaultdict

CSV_PATH = 'toy_panel_with_random_x.csv'
BETA=0.96
X_GRID = np.array([0.0,0.25,0.5,0.75,1.0])
J=len(X_GRID)
A_BINS,Y_BINS,AGE_BINS=6,4,4
ALPHA=5.0
H,DRAWS=3,30
K_TYPES=2
EULER_GAMMA=0.5772156649015329

## 1) Load the panel data

**Why**: We need a person–time panel with $(a,y,age,x)$ to build states and choices.

In [25]:
df = pd.read_csv(CSV_PATH)
df.head()

   id  t  age             a             y         x
0   0  0   49  22578.384369  18562.351115  0.986390
1   0  1   50  21927.092309  18448.435478  0.242381
2   0  2   51  21828.647582  18243.992208  0.702797
3   0  3   52  21654.901444  18939.917391  0.695454
4   0  4   53  21921.181994  18889.896102  0.009471

## 2) Define state bins and discretize actions

- CCPs and transitions are nonparametric objects. To estimate them robustly, we need a finite state grid. Quantile bins give balanced cells.
- A discrete action set $J=\{0,0.25,0.5,0.75,1\}$ makes logit CCPs tractable and aligns with Hotz–Miller.

In [26]:
def quantile_bins(series, nbins):
    qs = np.linspace(0,1,nbins+1)
    cuts = series.quantile(qs).values.astype(float)
    for i in range(1,len(cuts)):
        if cuts[i] <= cuts[i-1]:
            cuts[i] = cuts[i-1] + 1e-9
    return cuts

def cut_to_bins(x, cuts):
    return int(np.clip(np.searchsorted(cuts, x, side='right')-1, 0, len(cuts)-2))

def dirichlet_smooth(counts, alpha=5.0):
    counts = np.asarray(counts,float)
    prior = alpha/len(counts)
    return (counts + prior)/(counts.sum()+alpha)

def inclusive_value_from_ccp(P):
    P = np.clip(np.asarray(P,float), 1e-12,1-1e-12)
    return -float(np.log(P[0]))

def softmax(v):
    v = np.asarray(v,float); v = v - np.max(v)
    ex = np.exp(v); return ex/ex.sum()

In [27]:
a_cuts = quantile_bins(df['a'], A_BINS)
y_cuts = quantile_bins(df['y'], Y_BINS)
age_cuts = quantile_bins(df['age'], AGE_BINS)

dfb = df.copy()
dfb['ia'] = dfb['a'].apply(lambda v: cut_to_bins(v, a_cuts))
dfb['iy'] = dfb['y'].apply(lambda v: cut_to_bins(v, y_cuts))
dfb['iage'] = dfb['age'].apply(lambda v: cut_to_bins(v, age_cuts))

def x_to_j(x): 
    return int(np.argmin(np.abs(X_GRID - float(x))))

dfb['j'] = dfb['x'].apply(x_to_j)

dfb = dfb.sort_values(['id','t']).reset_index(drop=True)

for col in ['ia','iy','iage','j']:
    dfb[col+'_next'] = dfb.groupby('id')[col].shift(-1)

dfb = dfb.dropna(subset=['ia_next','iy_next','iage_next']).copy()

for col in ['ia_next','iy_next','iage_next','j_next']:
    dfb[col] = dfb[col].astype(int)

dfb.head()

,id,t,age,a,y,x,ia,iy,iage,j,ia_next,iy_next,iage_next,j_next
0,0,0,49,22578.384369,18562.351115,0.986390,2,0,2,4,2,0,2,1
1,0,1,50,21927.092309,18448.435478,0.242381,2,0,2,1,2,0,2,3
2,0,2,51,21828.647582,18243.992208,0.702797,2,0,2,3,2,1,2,3
3,0,3,52,21654.901444,18939.917391,0.695454,2,1,2,3,2,1,3,0
5,1,0,49,12187.260333,26335.488275,0.384359,0,3,2,2,0,3,2,3

## 3) Estimate CCP $\hat{P}(j \mid s)$

With logit shocks, CCPs invert to value-index differences and yield an inclusive value for the state. They are the data bridge to dynamic values.

In [29]:
J=len(X_GRID)
counts = defaultdict(lambda: np.zeros(J, float))

for _,row in dfb.iterrows():
    s=(int(row['ia']), int(row['iy']), int(row['iage']))
    j=int(row['j'])
    counts[s][j]+=1.0

ccp={}; state_counts={}

for s,cvec in counts.items():
    state_counts[s]=float(cvec.sum())
    ccp[s]=dirichlet_smooth(cvec, alpha=ALPHA)
len(ccp)

90

In [30]:
counts

defaultdict(<function __main__.<lambda>()>,
            {(2, 0, 2): array([1., 2., 0., 1., 1.]),
             (2, 1, 2): array([3., 2., 2., 3., 0.]),
             (0, 3, 2): array([1., 2., 2., 2., 2.]),
             (2, 1, 0): array([1., 6., 3., 2., 0.]),
             (1, 2, 1): array([0., 1., 0., 1., 1.]),
             (2, 2, 1): array([0., 2., 2., 2., 2.]),
             (4, 3, 0): array([1., 1., 1., 3., 3.]),
             (4, 3, 1): array([2., 1., 3., 2., 0.]),
             (0, 0, 1): array([1., 2., 5., 0., 2.]),
             (4, 1, 2): array([1., 0., 3., 2., 3.]),
             (5, 2, 3): array([2., 1., 3., 2., 1.]),
             (3, 0, 2): array([0., 0., 2., 4., 2.]),
             (5, 1, 1): array([1., 1., 1., 2., 0.]),
             (5, 2, 2): array([0., 1., 2., 1., 1.]),
             (5, 1, 2): array([0., 3., 0., 0., 1.]),
             (3, 2, 2): array([1., 1., 2., 2., 3.]),
             (1, 1, 1): array([0., 0., 0., 0., 1.]),
             (4, 3, 2): array([0., 2., 1., 2., 2.]),
             (1, 0, 3): array([0., 2., 1., 1., 0.]),
             (0, 3, 1): array([1., 2., 1., 2., 0.]),
             (5, 0, 0): array([1., 4., 3., 1., 4.]),
             (0, 0, 3): array([0., 2., 1., 1., 0.]),
             (0, 3, 0): array([2., 1., 2., 1., 3.]),
             (5, 0, 2): array([1., 1., 0., 3., 1.]),
             (0, 2, 2): array([3., 0., 0., 3., 1.]),
             (0, 1, 2): array([0., 1., 1., 0., 2.]),
             (1, 2, 2): array([0., 1., 2., 3., 1.]),
             (2, 2, 2): array([2., 4., 1., 2., 0.]),
             (3, 0, 1): array([0., 2., 1., 1., 1.]),
             (4, 0, 1): array([1., 5., 6., 0., 2.]),
             (5, 1, 3): array([1., 1., 2., 4., 0.]),
             (0, 0, 0): array([1., 0., 3., 3., 2.]),
             (0, 1, 0): array([2., 1., 1., 1., 3.]),
             (1, 1, 0): array([3., 1., 2., 5., 2.]),
             (1, 2, 0): array([0., 2., 1., 2., 0.]),
             (3, 3, 2): array([0., 2., 3., 4., 1.]),
             (2, 3, 2): array([0., 2., 1., 3., 0.]),
             (0, 3, 3): array([2., 1., 1., 0., 1.]),
             (5, 2, 1): array([1., 1., 0., 3., 1.]),
             (1, 1, 2): array([0., 2., 2., 1., 1.]),
             (2, 1, 3): array([0., 4., 3., 2., 0.]),
             (2, 1, 1): array([1., 5., 0., 0., 0.]),
             (3, 1, 2): array([0., 4., 2., 2., 1.]),
             (3, 0, 0): array([1., 3., 0., 2., 1.]),
             (5, 0, 3): array([3., 2., 2., 2., 0.]),
             (3, 3, 1): array([0., 0., 0., 1., 1.]),
             (2, 3, 1): array([0., 1., 2., 4., 0.]),
             (3, 2, 1): array([1., 2., 5., 2., 0.]),
             (3, 1, 3): array([0., 2., 2., 5., 3.]),
             (3, 2, 3): array([0., 0., 0., 0., 2.]),
             (5, 3, 1): array([0., 0., 1., 0., 0.]),
             (5, 3, 2): array([0., 1., 3., 2., 0.]),
             (4, 0, 0): array([0., 3., 1., 5., 1.]),
             (5, 0, 1): array([2., 1., 1., 1., 3.]),
             (1, 1, 3): array([0., 0., 1., 2., 0.]),
             (1, 3, 1): array([0., 1., 1., 0., 0.]),
             (1, 0, 1): array([2., 5., 2., 3., 2.]),
             (1, 2, 3): array([1., 4., 2., 1., 0.]),
             (2, 2, 3): array([0., 1., 0., 2., 1.]),
             (2, 0, 0): array([0., 0., 1., 0., 0.]),
             (2, 2, 0): array([1., 2., 1., 1., 2.]),
             (2, 3, 0): array([0., 2., 0., 2., 1.]),
             (3, 3, 0): array([1., 1., 1., 1., 0.]),
             (0, 2, 1): array([2., 3., 3., 0., 1.]),
             (4, 1, 3): array([2., 2., 0., 0., 2.]),
             (4, 2, 3): array([1., 2., 2., 3., 1.]),
             (4, 2, 0): array([1., 0., 1., 0., 2.]),
             (1, 3, 0): array([1., 2., 1., 1., 2.]),
             (1, 0, 0): array([0., 0., 1., 2., 1.]),
             (3, 3, 3): array([2., 4., 1., 2., 0.]),
             (2, 3, 3): array([0., 3., 2., 5., 1.]),
             (5, 2, 0): array([1., 2., 4., 3., 4.]),
             (0, 1, 3): array([0., 1., 1., 1., 1.]),
             (1, 3, 3): array([3., 3., 6., 3., 1.]),
             (5, 3, 0): array([1., 2., 0., 1., 0.]),
             (1, 3, 2): array([0., 3., 0., 1., 0.]),
             (0, 2, 3): array([0., 1., 0., 1., 0.]),
             (3, 0, 3): array([1., 0., 0., 1., 1.]),
             (4, 0, 3): array([2., 1., 1., 1., 1.]),
             (0, 0, 2): array([0., 2., 3., 1., 1.]),
             (0, 1, 1): array([0., 3., 4., 1., 1.]),
             (2, 0, 3): array([0., 3., 0., 0., 0.]),
             (4, 2, 1): array([0., 0., 5., 1., 0.]),
             (1, 0, 2): array([0., 1., 2., 1., 0.]),
             (3, 1, 1): array([2., 1., 1., 1., 0.]),
             (4, 1, 1): array([1., 0., 2., 1., 1.]),
             (4, 2, 2): array([0., 0., 1., 0., 1.]),
             (3, 2, 0): array([0., 0., 0., 0., 1.]),
             (3, 1, 0): array([0., 2., 0., 0., 0.]),
             (0, 2, 0): array([0., 3., 0., 0., 0.])})

In [31]:
ccp

{(2, 0, 2): array([0.2, 0.3, 0.1, 0.2, 0.2]),
 (2,
  1,
  2): array([0.26666667, 0.2       , 0.2       , 0.26666667, 0.06666667]),
 (0,
  3,
  2): array([0.14285714, 0.21428571, 0.21428571, 0.21428571, 0.21428571]),
 (2,
  1,
  0): array([0.11764706, 0.41176471, 0.23529412, 0.17647059, 0.05882353]),
 (1, 2, 1): array([0.125, 0.25 , 0.125, 0.25 , 0.25 ]),
 (2,
  2,
  1): array([0.07692308, 0.23076923, 0.23076923, 0.23076923, 0.23076923]),
 (4,
  3,
  0): array([0.14285714, 0.14285714, 0.14285714, 0.28571429, 0.28571429]),
 (4,
  3,
  1): array([0.23076923, 0.15384615, 0.30769231, 0.23076923, 0.07692308]),
 (0,
  0,
  1): array([0.13333333, 0.2       , 0.4       , 0.06666667, 0.2       ]),
 (4,
  1,
  2): array([0.14285714, 0.07142857, 0.28571429, 0.21428571, 0.28571429]),
 (5,
  2,
  3): array([0.21428571, 0.14285714, 0.28571429, 0.21428571, 0.14285714]),
 (3,
  0,
  2): array([0.07692308, 0.07692308, 0.23076923, 0.38461538, 0.23076923]),
 (5, 1, 1): array([0.2, 0.2, 0.2, 0.3, 0.1]),
 (5, 2, 2): array([0.1, 0.2, 0.3, 0.2, 0.2]),
 (5,
  1,
  2): array([0.11111111, 0.44444444, 0.11111111, 0.11111111, 0.22222222]),
 (3,
  2,
  2): array([0.14285714, 0.14285714, 0.21428571, 0.21428571, 0.28571429]),
 (1,
  1,
  1): array([0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.33333333]),
 (4,
  3,
  2): array([0.08333333, 0.25      , 0.16666667, 0.25      , 0.25      ]),
 (1,
  0,
  3): array([0.11111111, 0.33333333, 0.22222222, 0.22222222, 0.11111111]),
 (0,
  3,
  1): array([0.18181818, 0.27272727, 0.18181818, 0.27272727, 0.09090909]),
 (5,
  0,
  0): array([0.11111111, 0.27777778, 0.22222222, 0.11111111, 0.27777778]),
 (0,
  0,
  3): array([0.11111111, 0.33333333, 0.22222222, 0.22222222, 0.11111111]),
 (0,
  3,
  0): array([0.21428571, 0.14285714, 0.21428571, 0.14285714, 0.28571429]),
 (5,
  0,
  2): array([0.18181818, 0.18181818, 0.09090909, 0.36363636, 0.18181818]),
 (0,
  2,
  2): array([0.33333333, 0.08333333, 0.08333333, 0.33333333, 0.16666667]),
 (0,
  1,
  2): array([0.11111111, 0.22222222, 0.22222222, 0.11111111, 0.33333333]),
 (1,
  2,
  2): array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.16666667]),
 (2,
  2,
  2): array([0.21428571, 0.35714286, 0.14285714, 0.21428571, 0.07142857]),
 (3, 0, 1): array([0.1, 0.3, 0.2, 0.2, 0.2]),
 (4,
  0,
  1): array([0.10526316, 0.31578947, 0.36842105, 0.05263158, 0.15789474]),
 (5,
  1,
  3): array([0.15384615, 0.15384615, 0.23076923, 0.38461538, 0.07692308]),
 (0,
  0,
  0): array([0.14285714, 0.07142857, 0.28571429, 0.28571429, 0.21428571]),
 (0,
  1,
  0): array([0.23076923, 0.15384615, 0.15384615, 0.15384615, 0.30769231]),
 (1,
  1,
  0): array([0.22222222, 0.11111111, 0.16666667, 0.33333333, 0.16666667]),
 (1, 2, 0): array([0.1, 0.3, 0.2, 0.3, 0.1]),
 (3,
  3,
  2): array([0.06666667, 0.2       , 0.26666667, 0.33333333, 0.13333333]),
 (2,
  3,
  2): array([0.09090909, 0.27272727, 0.18181818, 0.36363636, 0.09090909]),
 (0, 3, 3): array([0.3, 0.2, 0.2, 0.1, 0.2]),
 (5,
  2,
  1): array([0.18181818, 0.18181818, 0.09090909, 0.36363636, 0.18181818]),
 (1,
  1,
  2): array([0.09090909, 0.27272727, 0.27272727, 0.18181818, 0.18181818]),
 (2,
  1,
  3): array([0.07142857, 0.35714286, 0.28571429, 0.21428571, 0.07142857]),
 (2,
  1,
  1): array([0.18181818, 0.54545455, 0.09090909, 0.09090909, 0.09090909]),
 (3,
  1,
  2): array([0.07142857, 0.35714286, 0.21428571, 0.21428571, 0.14285714]),
 (3,
  0,
  0): array([0.16666667, 0.33333333, 0.08333333, 0.25      , 0.16666667]),
 (5,
  0,
  3): array([0.28571429, 0.21428571, 0.21428571, 0.21428571, 0.07142857]),
 (3,
  3,
  1): array([0.14285714, 0.14285714, 0.14285714, 0.28571429, 0.28571429]),
 (2,
  3,
  1): array([0.08333333, 0.16666667, 0.25      , 0.41666667, 0.08333333]),
 (3,
  2,
  1): array([0.13333333, 0.2       , 0.4       , 0.2       , 0.06666667]),
 (3,
  1,
  3): array([0.05882353, 0.17647059, 0.17647059, 0.35294118, 0.23529412]),
 (3,
  2,
  3): array([0.14285714, 0.14285714, 0.14285714, 0.14285714, 0.42857143]),
 (5,
  3,
  1): array([0.16666667, 0.16666667, 0.33333333, 0.16666667, 0.16666667]),
 (5,
  3,
  2): array([0.09090909, 0.18181818, 0.36363636, 0.27272727, 0.09090909]),
 (4,
  0,
  0): array([0.06666667, 0.26666667, 0.13333333, 0.4       , 0.13333333]),
 (5,
  0,
  1): array([0.23076923, 0.15384615, 0.15384615, 0.15384615, 0.30769231]),
 (1, 1, 3): array([0.125, 0.125, 0.25 , 0.375, 0.125]),
 (1,
  3,
  1): array([0.14285714, 0.28571429, 0.28571429, 0.14285714, 0.14285714]),
 (1,
  0,
  1): array([0.15789474, 0.31578947, 0.15789474, 0.21052632, 0.15789474]),
 (1,
  2,
  3): array([0.15384615, 0.38461538, 0.23076923, 0.15384615, 0.07692308]),
 (2,
  2,
  3): array([0.11111111, 0.22222222, 0.11111111, 0.33333333, 0.22222222]),
 (2,
  0,
  0): array([0.16666667, 0.16666667, 0.33333333, 0.16666667, 0.16666667]),
 (2,
  2,
  0): array([0.16666667, 0.25      , 0.16666667, 0.16666667, 0.25      ]),
 (2, 3, 0): array([0.1, 0.3, 0.1, 0.3, 0.2]),
 (3,
  3,
  0): array([0.22222222, 0.22222222, 0.22222222, 0.22222222, 0.11111111]),
 (0,
  2,
  1): array([0.21428571, 0.28571429, 0.28571429, 0.07142857, 0.14285714]),
 (4,
  1,
  3): array([0.27272727, 0.27272727, 0.09090909, 0.09090909, 0.27272727]),
 (4,
  2,
  3): array([0.14285714, 0.21428571, 0.21428571, 0.28571429, 0.14285714]),
 (4,
  2,
  0): array([0.22222222, 0.11111111, 0.22222222, 0.11111111, 0.33333333]),
 (1,
  3,
  0): array([0.16666667, 0.25      , 0.16666667, 0.16666667, 0.25      ]),
 (1,
  0,
  0): array([0.11111111, 0.11111111, 0.22222222, 0.33333333, 0.22222222]),
 (3,
  3,
  3): array([0.21428571, 0.35714286, 0.14285714, 0.21428571, 0.07142857]),
 (2, 3, 3): array([0.0625, 0.25  , 0.1875, 0.375 , 0.125 ]),
 (5,
  2,
  0): array([0.10526316, 0.15789474, 0.26315789, 0.21052632, 0.26315789]),
 (0,
  1,
  3): array([0.11111111, 0.22222222, 0.22222222, 0.22222222, 0.22222222]),
 (1,
  3,
  3): array([0.19047619, 0.19047619, 0.33333333, 0.19047619, 0.0952381 ]),
 (5,
  3,
  0): array([0.22222222, 0.33333333, 0.11111111, 0.22222222, 0.11111111]),
 (1,
  3,
  2): array([0.11111111, 0.44444444, 0.11111111, 0.22222222, 0.11111111]),
 (0,
  2,
  3): array([0.14285714, 0.28571429, 0.14285714, 0.28571429, 0.14285714]),
 (3, 0, 3): array([0.25 , 0.125, 0.125, 0.25 , 0.25 ]),
 (4,
  0,
  3): array([0.27272727, 0.18181818, 0.18181818, 0.18181818, 0.18181818]),
 (0,
  0,
  2): array([0.08333333, 0.25      , 0.33333333, 0.16666667, 0.16666667]),
 (0,
  1,
  1): array([0.07142857, 0.28571429, 0.35714286, 0.14285714, 0.14285714]),
 (2, 0, 3): array([0.125, 0.5  , 0.125, 0.125, 0.125]),
 (4,
  2,
  1): array([0.09090909, 0.09090909, 0.54545455, 0.18181818, 0.09090909]),
 (1,
  0,
  2): array([0.11111111, 0.22222222, 0.33333333, 0.22222222, 0.11111111]),
 (3, 1, 1): array([0.3, 0.2, 0.2, 0.2, 0.1]),
 (4, 1, 1): array([0.2, 0.1, 0.3, 0.2, 0.2]),
 (4,
  2,
  2): array([0.14285714, 0.14285714, 0.28571429, 0.14285714, 0.28571429]),
 (3,
  2,
  0): array([0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.33333333]),
 (3,
  1,
  0): array([0.14285714, 0.42857143, 0.14285714, 0.14285714, 0.14285714]),
 (0, 2, 0): array([0.125, 0.5  , 0.125, 0.125, 0.125])}

## 4) Estimate transitions $\hat{p}(s' \mid s,j)$

To compute the continuation under “what if I choos $j$ now?”, we must know how states move given current state+action. We estimate it empirically from the panel.

In [32]:
trans = defaultdict(lambda: defaultdict(float))

for _, row in dfb.iterrows():
    s=(int(row['ia']), int(row['iy']), int(row['iage']))
    j=int(row['j'])
    sp=(int(row['ia_next']), int(row['iy_next']), int(row['iage_next']))
    trans[(s,j)][sp]+=1.0

trans_prob={}
for key,d in trans.items():
    items=list(d.items())
    probs=np.array([v for (_,v) in items], float); probs=probs/probs.sum()
    trans_prob[key]=([sp for (sp,_) in items], probs)

def draw_next_state(s,j):
    key=(s,j)
    if key not in trans_prob:
        cand=[(k,v) for (k,v) in trans_prob.items() if k[0]==s]
        if not cand:
            return s
        sps=[]; ps=[]
        for (_, (sp_list, p_list)) in cand:
            sps+=sp_list; ps+=list(p_list/len(cand))
        ps=np.array(ps,float); ps=ps/ps.sum()
        idx=np.random.choice(len(sps), p=ps)
        return sps[idx]
    sps,ps=trans_prob[key]
    idx=np.random.choice(len(sps), p=ps)
    return sps[idx]

In [33]:
trans_prob

{((2, 0, 2), 4): ([(2, 0, 2)], array([1.])),
 ((2, 0, 2), 1): ([(2, 0, 2), (2, 0, 3)], array([0.5, 0.5])),
 ((2, 0, 2), 3): ([(2, 1, 2)], array([1.])),
 ((2, 1, 2), 3): ([(2, 1, 3), (2, 1, 2), (3, 2, 2)],
  array([0.33333333, 0.33333333, 0.33333333])),
 ((0, 3, 2), 2): ([(0, 3, 2), (1, 3, 2)], array([0.5, 0.5])),
 ((0, 3, 2), 3): ([(0, 3, 2)], array([1.])),
 ((0, 3, 2), 1): ([(0, 3, 2)], array([1.])),
 ((0, 3, 2), 0): ([(0, 3, 3)], array([1.])),
 ((2, 1, 0), 1): ([(1, 2, 1), (2, 1, 0), (2, 1, 1)],
  array([0.16666667, 0.5       , 0.33333333])),
 ((1, 2, 1), 3): ([(2, 2, 1)], array([1.])),
 ((2, 2, 1), 3): ([(2, 2, 1), (1, 1, 1)], array([0.5, 0.5])),
 ((2, 2, 1), 4): ([(2, 2, 1), (3, 2, 1)], array([0.5, 0.5])),
 ((4, 3, 0), 4): ([(4, 3, 0)], array([1.])),
 ((4, 3, 0), 3): ([(4, 3, 1), (5, 3, 0), (4, 3, 0)],
  array([0.33333333, 0.33333333, 0.33333333])),
 ((4, 3, 1), 2): ([(4, 3, 1), (4, 3, 2)], array([0.66666667, 0.33333333])),
 ((4, 3, 1), 0): ([(4, 3, 1)], array([1.])),
 ((0, 0, 1), 2): ([(0, 0, 1), (1, 0, 1)], array([0.6, 0.4])),
 ((0, 0, 1), 1): ([(0, 0, 1), (0, 0, 2)], array([0.5, 0.5])),
 ((4, 1, 2), 2): ([(4, 1, 2)], array([1.])),
 ((4, 1, 2), 3): ([(4, 1, 2), (4, 1, 3)], array([0.5, 0.5])),
 ((4, 1, 2), 4): ([(4, 1, 2), (5, 1, 2)], array([0.66666667, 0.33333333])),
 ((5, 2, 3), 1): ([(5, 2, 3)], array([1.])),
 ((5, 2, 3), 2): ([(5, 2, 3)], array([1.])),
 ((5, 2, 3), 3): ([(5, 2, 3)], array([1.])),
 ((3, 0, 2), 3): ([(3, 0, 2), (4, 0, 2)], array([0.75, 0.25])),
 ((3, 0, 2), 2): ([(3, 0, 2)], array([1.])),
 ((3, 0, 2), 4): ([(3, 0, 2)], array([1.])),
 ((5, 1, 1), 3): ([(5, 1, 1)], array([1.])),
 ((5, 1, 1), 2): ([(5, 1, 1)], array([1.])),
 ((5, 1, 1), 1): ([(5, 1, 2)], array([1.])),
 ((5, 2, 2), 4): ([(5, 2, 2)], array([1.])),
 ((5, 2, 2), 3): ([(5, 2, 2)], array([1.])),
 ((5, 2, 2), 1): ([(5, 2, 2)], array([1.])),
 ((5, 2, 2), 2): ([(5, 2, 2), (5, 3, 2)], array([0.5, 0.5])),
 ((5, 1, 1), 0): ([(5, 1, 2)], array([1.])),
 ((5, 1, 2), 4): ([(5, 1, 2)], array([1.])),
 ((5, 1, 2), 1): ([(5, 1, 2), (5, 2, 2), (5, 0, 3)],
  array([0.33333333, 0.33333333, 0.33333333])),
 ((3, 2, 2), 1): ([(3, 2, 2)], array([1.])),
 ((3, 2, 2), 4): ([(3, 2, 2)], array([1.])),
 ((3, 2, 2), 3): ([(3, 2, 2)], array([1.])),
 ((3, 2, 2), 2): ([(3, 3, 2), (3, 1, 2)], array([0.5, 0.5])),
 ((2, 2, 1), 1): ([(2, 2, 1)], array([1.])),
 ((1, 1, 1), 4): ([(2, 1, 2)], array([1.])),
 ((2, 1, 2), 0): ([(2, 1, 2)], array([1.])),
 ((4, 3, 2), 4): ([(4, 3, 2)], array([1.])),
 ((4, 3, 2), 3): ([(4, 3, 2)], array([1.])),
 ((4, 3, 2), 2): ([(4, 3, 2)], array([1.])),
 ((1, 0, 3), 3): ([(1, 0, 3)], array([1.])),
 ((1, 0, 3), 2): ([(1, 0, 3)], array([1.])),
 ((1, 0, 3), 1): ([(1, 0, 3), (2, 0, 3)], array([0.5, 0.5])),
 ((0, 3, 1), 3): ([(0, 3, 1)], array([1.])),
 ((0, 3, 1), 2): ([(0, 3, 1)], array([1.])),
 ((0, 3, 1), 1): ([(0, 3, 1), (1, 3, 1)], array([0.5, 0.5])),
 ((5, 0, 0), 1): ([(5, 0, 0)], array([1.])),
 ((5, 0, 0), 4): ([(5, 0, 0), (5, 1, 0), (5, 0, 1)],
  array([0.5 , 0.25, 0.25])),
 ((0, 0, 3), 1): ([(0, 0, 3)], array([1.])),
 ((0, 0, 3), 3): ([(0, 0, 3)], array([1.])),
 ((0, 0, 3), 2): ([(0, 0, 3)], array([1.])),
 ((0, 3, 0), 2): ([(0, 3, 0), (1, 3, 0)], array([0.5, 0.5])),
 ((0, 3, 0), 3): ([(0, 3, 0)], array([1.])),
 ((0, 3, 0), 0): ([(0, 3, 0)], array([1.])),
 ((0, 3, 0), 4): ([(0, 3, 0), (1, 3, 0)], array([0.66666667, 0.33333333])),
 ((5, 0, 2), 3): ([(5, 0, 2), (4, 0, 2)], array([0.66666667, 0.33333333])),
 ((5, 0, 2), 0): ([(5, 0, 2)], array([1.])),
 ((5, 0, 2), 4): ([(5, 0, 3)], array([1.])),
 ((0, 2, 2), 0): ([(0, 2, 2), (1, 2, 2), (0, 2, 3)],
  array([0.33333333, 0.33333333, 0.33333333])),
 ((0, 2, 2), 3): ([(0, 2, 2)], array([1.])),
 ((0, 2, 2), 4): ([(0, 2, 2)], array([1.])),
 ((0, 1, 2), 1): ([(0, 1, 2)], array([1.])),
 ((0, 1, 2), 4): ([(0, 1, 2)], array([1.])),
 ((0, 1, 2), 2): ([(0, 1, 2)], array([1.])),
 ((1, 2, 2), 3): ([(1, 2, 2)], array([1.])),
 ((1, 2, 2), 2): ([(1, 2, 2), (0, 2, 2)], array([0.5, 0.5])),
 ((1, 2, 2), 4): ([(2, 2, 2)], array([1.])),
 ((2, 2, 2), 1): ([(2, 2, 2)], array([1.])),
 ((3, 0, 1), 1): ([(3, 0, 1), (4, 0, 1)], array([0.5, 0.5])),
 ((3, 0, 1), 2): ([(4, 0, 1)], array([1.])),
 ((4, 0, 1), 1): ([(4, 0, 1), (4, 1, 1)], array([0.8, 0.2])),
 ((4, 0, 1), 2): ([(4, 0, 1), (5, 0, 2)], array([0.83333333, 0.16666667])),
 ((5, 1, 3), 3): ([(5, 1, 3)], array([1.])),
 ((5, 1, 3), 2): ([(5, 2, 3), (5, 1, 3)], array([0.5, 0.5])),
 ((5, 2, 3), 0): ([(5, 2, 3)], array([1.])),
 ((0, 0, 0), 3): ([(0, 0, 0), (1, 0, 1), (1, 0, 0)],
  array([0.33333333, 0.33333333, 0.33333333])),
 ((0, 0, 0), 2): ([(0, 0, 0)], array([1.])),
 ((0, 0, 0), 0): ([(0, 0, 1)], array([1.])),
 ((4, 3, 1), 3): ([(4, 3, 1), (5, 2, 1)], array([0.5, 0.5])),
 ((4, 3, 1), 1): ([(4, 3, 1)], array([1.])),
 ((0, 1, 0), 0): ([(1, 1, 0), (0, 1, 0)], array([0.5, 0.5])),
 ((1, 1, 0), 4): ([(1, 1, 0), (1, 2, 0)], array([0.5, 0.5])),
 ((1, 1, 0), 1): ([(1, 1, 0)], array([1.])),
 ((1, 1, 0), 3): ([(1, 1, 0), (2, 1, 0)], array([0.8, 0.2])),
 ((1, 2, 0), 3): ([(1, 2, 0)], array([1.])),
 ((1, 2, 0), 1): ([(1, 2, 0)], array([1.])),
 ((3, 3, 2), 3): ([(2, 3, 2), (3, 3, 2)], array([0.25, 0.75])),
 ((2, 3, 2), 1): ([(2, 3, 2), (3, 3, 2)], array([0.5, 0.5])),
 ((3, 3, 2), 1): ([(3, 3, 2), (3, 2, 2)], array([0.5, 0.5])),
 ((0, 3, 2), 4): ([(0, 3, 3), (0, 3, 2)], array([0.5, 0.5])),
 ((0, 3, 3), 0): ([(0, 3, 3)], array([1.])),
 ((0, 3, 3), 2): ([(0, 3, 3)], array([1.])),
 ((5, 2, 1), 3): ([(5, 2, 1)], array([1.])),
 ((5, 2, 1), 1): ([(5, 2, 1)], array([1.])),
 ((1, 1, 2), 2): ([(2, 1, 2), (1, 1, 2)], array([0.5, 0.5])),
 ((2, 1, 2), 1): ([(2, 1, 3), (2, 1, 2)], array([0.5, 0.5])),
 ((2, 1, 3), 2): ([(2, 1, 3)], array([1.])),
 ((2, 1, 1), 1): ([(2, 1, 1), (3, 1, 2), (3, 1, 1)], array([0.2, 0.2, 0.6])),
 ((3, 1, 2), 1): ([(3, 1, 2), (4, 1, 2)], array([0.5, 0.5])),
 ((3, 0, 0), 3): ([(3, 0, 0)], array([1.])),
 ((3, 0, 0), 1): ([(3, 0, 0), (3, 0, 1), (4, 0, 0)],
  array([0.33333333, 0.33333333, 0.33333333])),
 ((3, 0, 0), 0): ([(3, 0, 0)], array([1.])),
 ((5, 0, 3), 0): ([(5, 0, 3), (5, 1, 3)], array([0.66666667, 0.33333333])),
 ((5, 0, 3), 3): ([(5, 0, 3)], array([1.])),
 ((5, 0, 3), 1): ([(5, 0, 3)], array([1.])),
 ((5, 0, 3), 2): ([(5, 0, 3)], array([1.])),
 ((3, 3, 1), 4): ([(2, 3, 1)], array([1.])),
 ((2, 3, 1), 1): ([(2, 3, 1)], array([1.])),
 ((2, 3, 1), 3): ([(2, 3, 1)], array([1.])),
 ((2, 3, 1), 2): ([(2, 3, 1)], array([1.])),
 ((3, 2, 1), 2): ([(3, 2, 1), (3, 2, 2)], array([0.8, 0.2])),
 ((1, 2, 0), 2): ([(1, 2, 1)], array([1.])),
 ((1, 2, 1), 1): ([(1, 2, 1)], array([1.])),
 ((1, 2, 1), 4): ([(1, 2, 1)], array([1.])),
 ((3, 1, 3), 4): ([(3, 1, 3), (4, 1, 3)], array([0.66666667, 0.33333333])),
 ((3, 1, 3), 3): ([(3, 1, 3), (2, 1, 3), (4, 1, 3)], array([0.6, 0.2, 0.2])),
 ((3, 1, 3), 1): ([(3, 2, 3), (4, 1, 3)], array([0.5, 0.5])),
 ((3, 2, 3), 4): ([(3, 2, 3)], array([1.])),
 ((2, 3, 2), 3): ([(2, 3, 2), (3, 3, 2)], array([0.66666667, 0.33333333])),
 ((2, 3, 2), 2): ([(3, 3, 2)], array([1.])),
 ((5, 3, 1), 2): ([(5, 3, 2)], array([1.])),
 ((5, 3, 2), 2): ([(5, 3, 2)], array([1.])),
 ((5, 3, 2), 3): ([(5, 3, 2), (5, 3, 3)], array([0.5, 0.5])),
 ((2, 2, 2), 0): ([(2, 3, 2), (2, 2, 2)], array([0.5, 0.5])),
 ((3, 3, 2), 4): ([(3, 3, 3)], array([1.])),
 ((2, 1, 3), 1): ([(2, 1, 3), (3, 1, 3)], array([0.75, 0.25])),
 ((2, 1, 3), 3): ([(3, 1, 3), (2, 1, 3)], array([0.5, 0.5])),
 ((4, 0, 0), 4): ([(4, 0, 1)], array([1.])),
 ((4, 0, 1), 4): ([(5, 0, 1), (4, 0, 1)], array([0.5, 0.5])),
 ((5, 0, 1), 0): ([(5, 0, 1)], array([1.])),
 ((1, 1, 2), 4): ([(1, 1, 3)], array([1.])),
 ((1, 1, 3), 3): ([(2, 1, 3), (1, 1, 3)], array([0.5, 0.5])),
 ((0, 3, 1), 0): ([(1, 3, 1)], array([1.])),
 ((1, 3, 1), 1): ([(0, 3, 1)], array([1.])),
 ((1, 3, 1), 2): ([(1, 3, 1)], array([1.])),
 ((1, 0, 1), 1): ([(1, 0, 1), (1, 0, 2)], array([0.8, 0.2])),
 ((1, 0, 1), 0): ([(1, 0, 1)], array([1.])),
 ((1, 2, 3), 3): ([(2, 2, 3)], array([1.])),
 ((2, 2, 3), 3): ([(2, 2, 3)], array([1.])),
 ((2, 2, 3), 1): ([(3, 2, 3)], array([1.])),
 ((2, 0, 0), 2): ([(1, 0, 1)], array([1.])),
 ((1, 0, 1), 2): ([(1, 0, 1)], array([1.])),
 ((1, 0, 1), 4): ([(1, 0, 1)], array([1.])),
 ((1, 0, 1), 3): ([(1, 0, 1)], array([1.])),
 ((2, 2, 0), 1): ([(2, 2, 0)], array([1.])),
 ((2, 2, 0), 4): ([(2, 3, 0), (2, 2, 0)], array([0.5, 0.5])),
 ((2, 3, 0), 3): ([(3, 3, 0), (2, 3, 0)], array([0.5, 0.5])),
 ((3, 3, 0), 2): ([(3, 3, 0)], array([1.])),
 ((0, 2, 1), 1): ([(0, 2, 1), (0, 3, 1)], array([0.66666667, 0.33333333])),
 ((0, 2, 1), 0): ([(0, 2, 1)], array([1.])),
 ((0, 2, 1), 2): ([(0, 2, 1)], array([1.])),
 ((1, 2, 3), 1): ([(2, 2, 3), (1, 2, 3), (0, 2, 3)],
  array([0.25, 0.5 , 0.25])),
 ((2, 2, 3), 4): ([(1, 2, 3)], array([1.])),
 ((3, 1, 3), 2): ([(3, 1, 3)], array([1.])),
 ((4, 1, 3), 4): ([(4, 2, 3), (4, 1, 3)], array([0.5, 0.5])),
 ((4, 2, 3), 1): ([(4, 2, 3)], array([1.])),
 ((4, 2, 0), 4): ([(4, 2, 0)], array([1.])),
 ((4, 2, 0), 0): ([(4, 2, 0)], array([1.])),
 ((4, 2, 0), 2): ([(4, 2, 0)], array([1.])),
 ((2, 2, 0), 0): ([(2, 1, 0)], array([1.])),
 ((2, 1, 0), 2): ([(2, 1, 0)], array([1.])),
 ((4, 3, 2), 1): ([(4, 3, 2)], array([1.])),
 ((2, 2, 2), 2): ([(2, 2, 2)], array([1.])),
 ((2, 2, 2), 3): ([(2, 2, 3)], array([1.])),
 ((3, 2, 1), 0): ([(3, 2, 2)], array([1.])),
 ((1, 1, 2), 1): ([(1, 1, 2), (1, 1, 3)], array([0.5, 0.5])),
 ((1, 1, 2), 3): ([(1, 1, 2)], array([1.])),
 ((1, 2, 3), 2): ([(1, 2, 3)], array([1.])),
 ((1, 2, 3), 0): ([(1, 2, 3)], array([1.])),
 ((0, 3, 0), 1): ([(0, 3, 0)], array([1.])),
 ((1, 3, 0), 0): ([(0, 3, 1)], array([1.])),
 ((4, 1, 3), 0): ([(4, 1, 3)], array([1.])),
 ((4, 1, 3), 1): ([(4, 1, 3)], array([1.])),
 ((5, 2, 3), 4): ([(5, 2, 3)], array([1.])),
 ((1, 0, 0), 3): ([(1, 0, 0)], array([1.])),
 ((1, 0, 0), 2): ([(1, 0, 0)], array([1.])),
 ((3, 3, 2), 2): ([(3, 3, 3), (3, 3, 2)], array([0.33333333, 0.66666667])),
 ((3, 3, 3), 1): ([(2, 3, 3), (3, 3, 3)], array([0.25, 0.75])),
 ((2, 3, 3), 2): ([(3, 3, 3), (2, 3, 3)], array([0.5, 0.5])),
 ((3, 3, 3), 0): ([(3, 3, 3)], array([1.])),
 ((5, 2, 0), 1): ([(5, 2, 1), (5, 2, 0)], array([0.5, 0.5])),
 ((5, 2, 1), 4): ([(5, 2, 1)], array([1.])),
 ((5, 2, 1), 0): ([(5, 2, 1)], array([1.])),
 ((0, 1, 3), 3): ([(0, 1, 3)], array([1.])),
 ((0, 1, 3), 2): ([(0, 1, 3)], array([1.])),
 ((0, 1, 3), 4): ([(0, 1, 3)], array([1.])),
 ((0, 1, 3), 1): ([(0, 1, 3)], array([1.])),
 ((5, 1, 3), 0): ([(5, 1, 3)], array([1.])),
 ((1, 3, 3), 2): ([(1, 3, 3), (2, 3, 3)], array([0.5, 0.5])),
 ((1, 3, 3), 3): ([(2, 3, 3), (1, 3, 3)], array([0.33333333, 0.66666667])),
 ((2, 3, 3), 1): ([(1, 3, 3), (2, 3, 3)], array([0.66666667, 0.33333333])),
 ((1, 3, 3), 1): ([(2, 3, 3), (1, 3, 3)], array([0.33333333, 0.66666667])),
 ((2, 3, 3), 3): ([(2, 3, 3), (3, 3, 3)], array([0.8, 0.2])),
 ((1, 3, 3), 0): ([(1, 3, 3)], array([1.])),
 ((5, 3, 0), 1): ([(5, 2, 0), (4, 3, 0)], array([0.5, 0.5])),
 ((5, 2, 0), 2): ([(5, 2, 0)], array([1.])),
 ((5, 2, 0), 3): ([(5, 3, 0), (5, 2, 0)], array([0.33333333, 0.66666667])),
 ((3, 3, 3), 2): ([(2, 3, 3)], array([1.])),
 ((1, 0, 0), 4): ([(1, 0, 1)], array([1.])),
 ((1, 3, 0), 1): ([(1, 3, 0)], array([1.])),
 ((1, 3, 0), 4): ([(1, 3, 0)], array([1.])),
 ((1, 1, 0), 2): ([(1, 1, 0)], array([1.])),
 ((2, 1, 0), 3): ([(2, 1, 1), (2, 1, 0)], array([0.5, 0.5])),
 ((4, 2, 3), 4): ([(4, 2, 3)], array([1.])),
 ((4, 2, 3), 3): ([(4, 2, 3)], array([1.])),
 ((4, 2, 3), 0): ([(4, 2, 3)], array([1.])),
 ((3, 0, 1), 3): ([(3, 0, 1)], array([1.])),
 ((1, 3, 2), 1): ([(1, 3, 2), (2, 3, 2)], array([0.66666667, 0.33333333])),
 ((1, 3, 2), 3): ([(1, 3, 2)], array([1.])),
 ((0, 2, 3), 3): ([(1, 3, 3)], array([1.])),
 ((4, 0, 0), 1): ([(4, 0, 0), (4, 0, 1)], array([0.66666667, 0.33333333])),
 ((4, 0, 0), 3): ([(4, 0, 0), (3, 0, 0), (4, 0, 1)], array([0.6, 0.2, 0.2])),
 ((3, 0, 3), 3): ([(3, 0, 3)], array([1.])),
 ((3, 0, 3), 0): ([(4, 0, 3)], array([1.])),
 ((4, 0, 3), 2): ([(4, 0, 3)], array([1.])),
 ((4, 0, 3), 0): ([(4, 0, 3)], array([1.])),
 ((0, 0, 2), 1): ([(0, 0, 2)], array([1.])),
 ((0, 0, 2), 4): ([(0, 0, 2)], array([1.])),
 ((4, 2, 3), 2): ([(4, 2, 3)], array([1.])),
 ((4, 3, 0), 0): ([(5, 3, 0)], array([1.])),
 ((4, 3, 0), 2): ([(4, 3, 0)], array([1.])),
 ((5, 3, 2), 1): ([(5, 3, 2)], array([1.])),
 ((4, 0, 3), 1): ([(4, 0, 3)], array([1.])),
 ((4, 0, 3), 4): ([(4, 0, 3)], array([1.])),
 ((4, 0, 3), 3): ([(4, 0, 3)], array([1.])),
 ((5, 2, 0), 4): ([(5, 3, 0), (5, 2, 0)], array([0.25, 0.75])),
 ((5, 3, 0), 0): ([(5, 3, 0)], array([1.])),
 ((5, 3, 0), 3): ([(5, 3, 0)], array([1.])),
 ((0, 1, 1), 2): ([(0, 1, 1)], array([1.])),
 ((0, 1, 1), 4): ([(0, 1, 1)], array([1.])),
 ((2, 0, 3), 1): ([(2, 0, 3), (3, 0, 3)], array([0.66666667, 0.33333333])),
 ((3, 0, 3), 4): ([(3, 0, 3)], array([1.])),
 ((3, 2, 2), 0): ([(3, 2, 2)], array([1.])),
 ((0, 2, 3), 1): ([(1, 2, 3)], array([1.])),
 ((4, 2, 1), 3): ([(4, 2, 1)], array([1.])),
 ((4, 2, 1), 2): ([(4, 2, 1), (5, 2, 1), (4, 2, 2)], array([0.6, 0.2, 0.2])),
 ((2, 2, 1), 2): ([(2, 2, 1), (3, 2, 1)], array([0.5, 0.5])),
 ((3, 2, 1), 1): ([(3, 2, 1), (4, 2, 1)], array([0.5, 0.5])),
 ((0, 0, 2), 3): ([(0, 0, 2)], array([1.])),
 ((0, 0, 2), 2): ([(0, 0, 2), (1, 0, 2)], array([0.66666667, 0.33333333])),
 ((5, 1, 3), 1): ([(5, 1, 3)], array([1.])),
 ((1, 1, 0), 0): ([(1, 1, 0), (2, 1, 0)], array([0.33333333, 0.66666667])),
 ((5, 2, 0), 0): ([(5, 2, 0)], array([1.])),
 ((0, 1, 0), 3): ([(0, 1, 0)], array([1.])),
 ((0, 1, 0), 1): ([(0, 1, 0)], array([1.])),
 ((0, 1, 0), 4): ([(0, 1, 1), (0, 1, 0), (1, 1, 0)],
  array([0.33333333, 0.33333333, 0.33333333])),
 ((0, 1, 1), 1): ([(0, 1, 1)], array([1.])),
 ((1, 0, 2), 2): ([(1, 0, 2), (1, 1, 3)], array([0.5, 0.5])),
 ((1, 0, 2), 1): ([(2, 0, 2)], array([1.])),
 ((2, 0, 2), 0): ([(2, 0, 2)], array([1.])),
 ((5, 0, 2), 1): ([(5, 0, 2)], array([1.])),
 ((2, 1, 2), 2): ([(2, 1, 2), (3, 2, 2)], array([0.5, 0.5])),
 ((3, 3, 3), 3): ([(3, 3, 3), (4, 3, 3)], array([0.5, 0.5])),
 ((5, 0, 0), 2): ([(5, 0, 0)], array([1.])),
 ((3, 1, 1), 0): ([(2, 1, 1), (3, 1, 1)], array([0.5, 0.5])),
 ((5, 0, 0), 0): ([(5, 0, 0)], array([1.])),
 ((5, 0, 0), 3): ([(5, 0, 0)], array([1.])),
 ((5, 0, 1), 4): ([(5, 0, 1)], array([1.])),
 ((5, 0, 1), 3): ([(5, 0, 1)], array([1.])),
 ((1, 0, 2), 3): ([(1, 0, 2)], array([1.])),
 ((1, 1, 3), 2): ([(1, 1, 3)], array([1.])),
 ((2, 3, 0), 4): ([(2, 3, 0)], array([1.])),
 ((2, 3, 0), 1): ([(2, 3, 0)], array([1.])),
 ((1, 3, 0), 3): ([(1, 3, 0)], array([1.])),
 ((1, 3, 0), 2): ([(1, 3, 0)], array([1.])),
 ((3, 1, 1), 3): ([(3, 1, 2)], array([1.])),
 ((3, 1, 2), 3): ([(3, 1, 2), (4, 1, 2)], array([0.5, 0.5])),
 ((3, 1, 2), 4): ([(3, 2, 2)], array([1.])),
 ((4, 1, 1), 3): ([(4, 1, 1)], array([1.])),
 ((4, 1, 1), 2): ([(4, 1, 1)], array([1.])),
 ((4, 1, 1), 4): ([(4, 1, 1)], array([1.])),
 ((0, 1, 1), 3): ([(0, 1, 1)], array([1.])),
 ((5, 0, 1), 1): ([(5, 0, 1)], array([1.])),
 ((5, 0, 1), 2): ([(5, 0, 1)], array([1.])),
 ((2, 3, 3), 4): ([(2, 3, 3)], array([1.])),
 ((3, 1, 2), 2): ([(3, 1, 2)], array([1.])),
 ((3, 2, 1), 3): ([(3, 2, 1)], array([1.])),
 ((3, 3, 0), 3): ([(3, 3, 0)], array([1.])),
 ((3, 3, 0), 1): ([(3, 3, 0)], array([1.])),
 ((3, 3, 0), 0): ([(3, 3, 1)], array([1.])),
 ((3, 3, 1), 3): ([(3, 3, 1)], array([1.])),
 ((4, 2, 2), 2): ([(4, 2, 2)], array([1.])),
 ((4, 2, 2), 4): ([(4, 2, 2)], array([1.])),
 ((2, 2, 0), 2): ([(2, 2, 0)], array([1.])),
 ((2, 2, 0), 3): ([(3, 2, 0)], array([1.])),
 ((3, 2, 0), 4): ([(3, 3, 0)], array([1.])),
 ((4, 3, 0), 1): ([(4, 3, 0)], array([1.])),
 ((4, 1, 2), 0): ([(4, 1, 3)], array([1.])),
 ((3, 0, 0), 4): ([(3, 0, 1)], array([1.])),
 ((3, 0, 1), 4): ([(3, 1, 1)], array([1.])),
 ((4, 0, 0), 2): ([(4, 0, 0)], array([1.])),
 ((1, 2, 2), 1): ([(2, 2, 2)], array([1.])),
 ((2, 1, 1), 0): ([(2, 1, 1)], array([1.])),
 ((3, 1, 0), 1): ([(3, 1, 0), (3, 1, 1)], array([0.5, 0.5])),
 ((3, 1, 1), 1): ([(4, 1, 1)], array([1.])),
 ((4, 1, 1), 0): ([(4, 1, 1)], array([1.])),
 ((3, 1, 1), 2): ([(4, 0, 1)], array([1.])),
 ((4, 0, 1), 0): ([(4, 0, 1)], array([1.])),
 ((0, 0, 0), 4): ([(0, 0, 1)], array([1.])),
 ((0, 0, 1), 4): ([(0, 0, 1)], array([1.])),
 ((0, 0, 1), 0): ([(0, 0, 1)], array([1.])),
 ((2, 1, 0), 0): ([(3, 2, 1)], array([1.])),
 ((0, 1, 0), 2): ([(0, 1, 0)], array([1.])),
 ((0, 2, 0), 1): ([(0, 2, 0), (0, 2, 1)], array([0.66666667, 0.33333333])),
 ((0, 3, 3), 1): ([(0, 3, 3)], array([1.])),
 ((0, 3, 3), 4): ([(1, 3, 3)], array([1.])),
 ((1, 3, 3), 4): ([(1, 3, 3)], array([1.])),
 ((0, 2, 1), 4): ([(0, 2, 1)], array([1.]))}

## 5) Compute inclusive values and CCS $\Delta EV (s ; j,0)$

Under logit, the $\textbf{ex-ante value}$ at a state is
$$V(s) = \gamma_E - \ln P(0 \mid s)$$
So we can $\textbf{simulate forward}$ using $\hat{P}$ and $\hat{p}$, summing discounted $\textbf{inclusive values}$, instead of solving Bellman.

In [34]:
states=list(ccp.keys())

def delta_ev_ccs(s,j):
    def path_val(start_s, initial_j):
        vals=[]
        for _ in range(DRAWS):
            s_current=draw_next_state(start_s, initial_j)
            acc=(BETA**1)*inclusive_value_from_ccp(ccp.get(s_current, np.ones(J)/J))
            for h in range(2,H+1):
                P_current=ccp.get(s_current, None)
                if P_current is None:
                    j_draw=0
                else:
                    j_draw=int(np.random.choice(J, p=P_current))
                s_current=draw_next_state(s_current, j_draw)
                acc+=(BETA**h)*inclusive_value_from_ccp(ccp.get(s_current, np.ones(J)/J))
            vals.append(acc)
        return float(np.mean(vals)) if vals else 0.0
    return path_val(s,j) - path_val(s,0)

delta_cache={}
for s in states:
    for j in range(1,J):
        delta_cache[(s,j)] = delta_ev_ccs(s,j)

len(delta_cache)

360

In [35]:
delta_cache

{((2, 0, 2), 1): 0.19720967912856935,
 ((2, 0, 2), 2): 0.5791851632731007,
 ((2, 0, 2), 3): 0.07204103934853556,
 ((2, 0, 2), 4): -0.03557486668826382,
 ((2, 1, 2), 1): 1.2272568069367376,
 ((2, 1, 2), 2): 0.658642390850769,
 ((2, 1, 2), 3): 1.7784544509508855,
 ((2, 1, 2), 4): 0.5138791065076767,
 ((0, 3, 2), 1): 1.4778681083332827,
 ((0, 3, 2), 2): 1.8365690531058068,
 ((0, 3, 2), 3): 1.2467713331719095,
 ((0, 3, 2), 4): 0.5817881110855581,
 ((2, 1, 0), 1): -0.13536077659242185,
 ((2, 1, 0), 2): -0.08463240858545706,
 ((2, 1, 0), 3): -0.3693196559303873,
 ((2, 1, 0), 4): -0.2726579976479391,
 ((1, 2, 1), 1): -0.06176033521758395,
 ((1, 2, 1), 2): -0.1429474643204891,
 ((1, 2, 1), 3): 0.20327197171158407,
 ((1, 2, 1), 4): -0.2063592052167369,
 ((2, 2, 1), 1): 0.6901614253644874,
 ((2, 2, 1), 2): -0.1336645143905697,
 ((2, 2, 1), 3): -0.7540518519683888,
 ((2, 2, 1), 4): 0.12997191644425587,
 ((4, 3, 0), 1): 0.37743169539129706,
 ((4, 3, 0), 2): 0.3669249225588507,
 ((4, 3, 0), 3): 0.004966662671037625,
 ((4, 3, 0), 4): 0.32757698933587687,
 ((4, 3, 1), 1): -0.08537296093930102,
 ((4, 3, 1), 2): 1.018778700468573,
 ((4, 3, 1), 3): 0.18308658486118468,
 ((4, 3, 1), 4): 0.2960581111612717,
 ((0, 0, 1), 1): 0.45956016034986913,
 ((0, 0, 1), 2): -0.06871884117718885,
 ((0, 0, 1), 3): 0.18695834856253857,
 ((0, 0, 1), 4): -0.11214924905820567,
 ((4, 1, 2), 1): 0.6899064941773907,
 ((4, 1, 2), 2): 1.2543609686681294,
 ((4, 1, 2), 3): 0.7730761864298881,
 ((4, 1, 2), 4): 1.3692705838362835,
 ((5, 2, 3), 1): 0.0,
 ((5, 2, 3), 2): 0.0,
 ((5, 2, 3), 3): 0.0,
 ((5, 2, 3), 4): 0.0,
 ((3, 0, 2), 1): -0.09045712188701227,
 ((3, 0, 2), 2): 0.29730012423330443,
 ((3, 0, 2), 3): -0.6976792943378571,
 ((3, 0, 2), 4): 0.37939155231681454,
 ((5, 1, 1), 1): -0.07247949381362595,
 ((5, 1, 1), 2): -0.7830677167040507,
 ((5, 1, 1), 3): -0.7331308395062068,
 ((5, 1, 1), 4): 0.06951125230366806,
 ((5, 2, 2), 1): -0.040776287357179974,
 ((5, 2, 2), 2): 0.00891570344438275,
 ((5, 2, 2), 3): 0.10473920928750413,
 ((5, 2, 2), 4): -0.02947440224360065,
 ((5, 1, 2), 1): -0.32323964135344774,
 ((5, 1, 2), 2): -0.1998266245818865,
 ((5, 1, 2), 3): 0.31278089238685336,
 ((5, 1, 2), 4): 0.06038529239579127,
 ((3, 2, 2), 1): -0.09256110869343459,
 ((3, 2, 2), 2): 1.07133090721383,
 ((3, 2, 2), 3): -0.009473401447453789,
 ((3, 2, 2), 4): -0.038981849794685,
 ((1, 1, 1), 1): 0.13172518565362612,
 ((1, 1, 1), 2): -0.22972540163089405,
 ((1, 1, 1), 3): 0.4182440313498157,
 ((1, 1, 1), 4): -0.07589077692778368,
 ((4, 3, 2), 1): 0.0,
 ((4, 3, 2), 2): 0.0,
 ((4, 3, 2), 3): 0.0,
 ((4, 3, 2), 4): 0.0,
 ((1, 0, 3), 1): -0.3033521446827203,
 ((1, 0, 3), 2): 0.1614659037088293,
 ((1, 0, 3), 3): 0.25922847108407154,
 ((1, 0, 3), 4): 0.03764966139676318,
 ((0, 3, 1), 1): -0.11046071092653076,
 ((0, 3, 1), 2): -0.24603623137962405,
 ((0, 3, 1), 3): -0.22529243590046377,
 ((0, 3, 1), 4): -0.2186124398562841,
 ((5, 0, 0), 1): -0.10527590674276688,
 ((5, 0, 0), 2): -0.025774965291912366,
 ((5, 0, 0), 3): -0.10589619193787136,
 ((5, 0, 0), 4): -0.9335239283584835,
 ((0, 0, 3), 1): 0.0,
 ((0, 0, 3), 2): 0.0,
 ((0, 0, 3), 3): 0.0,
 ((0, 0, 3), 4): 0.0,
 ((0, 3, 0), 1): -0.05796170329535233,
 ((0, 3, 0), 2): 0.17869138046791466,
 ((0, 3, 0), 3): -0.043138575160717174,
 ((0, 3, 0), 4): 0.08466682563012373,
 ((5, 0, 2), 1): 0.07042993021379473,
 ((5, 0, 2), 2): -0.1680790330571087,
 ((5, 0, 2), 3): 0.07255347435175263,
 ((5, 0, 2), 4): -0.9609103295950225,
 ((0, 2, 2), 1): -1.289916629562177,
 ((0, 2, 2), 2): -0.9533373252051018,
 ((0, 2, 2), 3): -1.1037385101460897,
 ((0, 2, 2), 4): -0.6991829787000015,
 ((0, 1, 2), 1): 0.0,
 ((0, 1, 2), 2): 0.0,
 ((0, 1, 2), 3): 0.0,
 ((0, 1, 2), 4): 0.0,
 ((1, 2, 2), 1): -0.3094463727518004,
 ((1, 2, 2), 2): -0.05748575215239349,
 ((1, 2, 2), 3): 1.1069167205117783,
 ((1, 2, 2), 4): -0.05214583715049059,
 ((2, 2, 2), 1): -0.8461721556805042,
 ((2, 2, 2), 2): -1.327528335721107,
 ((2, 2, 2), 3): -0.3190878308966898,
 ((2, 2, 2), 4): -1.0965062112008548,
 ((3, 0, 1), 1): 0.4924212168245061,
 ((3, 0, 1), 2): 0.5354770587794864,
 ((3, 0, 1), 3): 0.39075094573759106,
 ((3, 0, 1), 4): -0.6329712019713556,
 ((4, 0, 1), 1): -0.226865709769708,
 ((4, 0, 1), 2): -0.14751670551489227,
 ((4, 0, 1), 3): -0.1230253367683165,
 ((4, 0, 1), 4): -0.7015397991040171,
 ((5, 1, 3), 1): 0.00936494791919884,
 ((5, 1, 3), 2): -0.4990567173752751,
 ((5, 1, 3), 3): -0.048860597839297526,
 ((5, 1, 3), 4): -0.11244723697182923,
 ((0, 0, 0), 1): -0.1431234384601332,
 ((0, 0, 0), 2): -0.18524796295855683,
 ((0, 0, 0), 3): -0.17336508288519603,
 ((0, 0, 0), 4): -0.08958152421574717,
 ((0, 1, 0), 1): -0.4539861979093853,
 ((0, 1, 0), 2): -0.173900909225849,
 ((0, 1, 0), 3): -0.07510699823674649,
 ((0, 1, 0), 4): 1.1574999580246024,
 ((1, 1, 0), 1): -0.6771585615101969,
 ((1, 1, 0), 2): -0.5997000940857884,
 ((1, 1, 0), 3): -0.2999374719221892,
 ((1, 1, 0), 4): 0.10073493298050717,
 ((1, 2, 0), 1): 0.11470325495168598,
 ((1, 2, 0), 2): -0.09186407501910754,
 ((1, 2, 0), 3): 0.10412215362129285,
 ((1, 2, 0), 4): -0.054415826251221766,
 ((3, 3, 2), 1): -0.4011224548447334,
 ((3, 3, 2), 2): 0.5449217087793166,
 ((3, 3, 2), 3): 0.6098693632212786,
 ((3, 3, 2), 4): -1.4262646305376112,
 ((2, 3, 2), 1): -0.08395002659465867,
 ((2, 3, 2), 2): 0.013940814406446123,
 ((2, 3, 2), 3): 0.05034009049704391,
 ((2, 3, 2), 4): 0.11036637859794762,
 ((0, 3, 3), 1): -0.004815766417213041,
 ((0, 3, 3), 2): 0.16669054120387727,
 ((0, 3, 3), 3): 0.35930690656826014,
 ((0, 3, 3), 4): 1.6349180201426128,
 ((5, 2, 1), 1): 0.0,
 ((5, 2, 1), 2): 0.0,
 ((5, 2, 1), 3): 0.0,
 ((5, 2, 1), 4): 0.0,
 ((1, 1, 2), 1): 0.20181531010154252,
 ((1, 1, 2), 2): -0.7205273050125278,
 ((1, 1, 2), 3): 0.12488622261050075,
 ((1, 1, 2), 4): 0.048162999324076416,
 ((2, 1, 3), 1): -0.09459339881607587,
 ((2, 1, 3), 2): 0.08388518214531704,
 ((2, 1, 3), 3): -0.07569596094332187,
 ((2, 1, 3), 4): 0.10908633804091661,
 ((2, 1, 1), 1): 0.3213394163530445,
 ((2, 1, 1), 2): -0.18868413436794373,
 ((2, 1, 1), 3): 0.09420201843607323,
 ((2, 1, 1), 4): 0.16891471482471054,
 ((3, 1, 2), 1): 0.11309204475110768,
 ((3, 1, 2), 2): 0.786728442603942,
 ((3, 1, 2), 3): 0.05520393348107433,
 ((3, 1, 2), 4): -0.21387281048225848,
 ((3, 0, 0), 1): 0.7211546347355133,
 ((3, 0, 0), 2): 0.25034363862053954,
 ((3, 0, 0), 3): 0.20002282838710173,
 ((3, 0, 0), 4): 0.276018751392618,
 ((5, 0, 3), 1): -0.42744331363726173,
 ((5, 0, 3), 2): -0.7166993044426238,
 ((5, 0, 3), 3): -0.5432715170195972,
 ((5, 0, 3), 4): -0.45651662991812225,
 ((3, 3, 1), 1): -0.13320888878267834,
 ((3, 3, 1), 2): 0.06761172105190738,
 ((3, 3, 1), 3): -0.5535054241380113,
 ((3, 3, 1), 4): 0.5223764358332943,
 ((2, 3, 1), 1): 0.0,
 ((2, 3, 1), 2): 0.0,
 ((2, 3, 1), 3): 0.0,
 ((2, 3, 1), 4): 0.0,
 ((3, 2, 1), 1): 0.10539536506164904,
 ((3, 2, 1), 2): -0.01927868701847313,
 ((3, 2, 1), 3): -0.0385228693802544,
 ((3, 2, 1), 4): 0.027002840813794116,
 ((3, 1, 3), 1): -1.1863124414788242,
 ((3, 1, 3), 2): 0.6766319689765572,
 ((3, 1, 3), 3): 0.39062010046695406,
 ((3, 1, 3), 4): -0.11111998378781696,
 ((3, 2, 3), 1): 0.0,
 ((3, 2, 3), 2): 0.0,
 ((3, 2, 3), 3): 0.0,
 ((3, 2, 3), 4): 0.0,
 ((5, 3, 1), 1): -0.11820048133870564,
 ((5, 3, 1), 2): -0.045536251007533224,
 ((5, 3, 1), 3): 0.14339074785350991,
 ((5, 3, 1), 4): 0.023252553705974677,
 ((5, 3, 2), 1): 0.3877444068504996,
 ((5, 3, 2), 2): -0.045495881990682996,
 ((5, 3, 2), 3): -0.48765772355585923,
 ((5, 3, 2), 4): 0.18997659329916328,
 ((4, 0, 0), 1): 0.43754129380816664,
 ((4, 0, 0), 2): 0.1302180142781122,
 ((4, 0, 0), 3): -0.01696351967090237,
 ((4, 0, 0), 4): -0.6767020240397326,
 ((5, 0, 1), 1): 0.0,
 ((5, 0, 1), 2): 0.0,
 ((5, 0, 1), 3): 0.0,
 ((5, 0, 1), 4): 0.0,
 ((1, 1, 3), 1): -0.019340321631049484,
 ((1, 1, 3), 2): -0.32592602814504446,
 ((1, 1, 3), 3): 0.2893038593480517,
 ((1, 1, 3), 4): 0.015527828579508629,
 ((1, 3, 1), 1): -0.18715101671288714,
 ((1, 3, 1), 2): 0.1249690202646363,
 ((1, 3, 1), 3): 0.0638242135903484,
 ((1, 3, 1), 4): -0.024633257131503328,
 ((1, 0, 1), 1): 0.06574969099759365,
 ((1, 0, 1), 2): -0.042666168178808306,
 ((1, 0, 1), 3): -0.03884261382679721,
 ((1, 0, 1), 4): 0.045382204835100914,
 ((1, 2, 3), 1): 0.11583909835356465,
 ((1, 2, 3), 2): 0.0013857749370727035,
 ((1, 2, 3), 3): 0.3994687652247837,
 ((1, 2, 3), 4): 0.09591936937487677,
 ((2, 2, 3), 1): -0.11806548440627385,
 ((2, 2, 3), 2): 0.04958501565662843,
 ((2, 2, 3), 3): 0.2724984685475347,
 ((2, 2, 3), 4): -0.15655811998894809,
 ((2, 0, 0), 1): -0.01725272765947672,
 ((2, 0, 0), 2): -0.02839766203400096,
 ((2, 0, 0), 3): 0.04877396146376434,
 ((2, 0, 0), 4): 0.017766331815307623,
 ((2, 2, 0), 1): -0.4667797870315544,
 ((2, 2, 0), 2): -0.5838012636848893,
 ((2, 2, 0), 3): -1.063468325219426,
 ((2, 2, 0), 4): 0.09617537536877574,
 ((2, 3, 0), 1): 0.2984563577647803,
 ((2, 3, 0), 2): -0.01652279027844994,
 ((2, 3, 0), 3): -0.09679728938320586,
 ((2, 3, 0), 4): 0.3620420349436264,
 ((3, 3, 0), 1): -1.331065257270879,
 ((3, 3, 0), 2): -1.563227012504167,
 ((3, 3, 0), 3): -1.4916828522072167,
 ((3, 3, 0), 4): -1.1700617825463153,
 ((0, 2, 1), 1): 0.26303395211280733,
 ((0, 2, 1), 2): 0.022254327657001305,
 ((0, 2, 1), 3): 0.022659117864997746,
 ((0, 2, 1), 4): 0.02669603062439041,
 ((4, 1, 3), 1): 0.019864386506497578,
 ((4, 1, 3), 2): 0.29650907592032194,
 ((4, 1, 3), 3): 0.47542098372217634,
 ((4, 1, 3), 4): 0.7211434448075518,
 ((4, 2, 3), 1): 0.0,
 ((4, 2, 3), 2): 0.0,
 ((4, 2, 3), 3): 0.0,
 ((4, 2, 3), 4): 0.0,
 ((4, 2, 0), 1): 0.0,
 ((4, 2, 0), 2): 0.0,
 ((4, 2, 0), 3): 0.0,
 ((4, 2, 0), 4): 0.0,
 ((1, 3, 0), 1): 0.0846049931229409,
 ((1, 3, 0), 2): 0.021009988277934433,
 ((1, 3, 0), 3): 0.024079608736914615,
 ((1, 3, 0), 4): 0.05133834966332884,
 ((1, 0, 0), 1): -0.10669002081017176,
 ((1, 0, 0), 2): 0.28126224204475925,
 ((1, 0, 0), 3): 0.014357274301266543,
 ((1, 0, 0), 4): -0.41322108011338354,
 ((3, 3, 3), 1): 0.6973265287385502,
 ((3, 3, 3), 2): 1.6006973336974237,
 ((3, 3, 3), 3): -0.3572472938737601,
 ((3, 3, 3), 4): 0.636726258908908,
 ((2, 3, 3), 1): -0.5852754962327937,
 ((2, 3, 3), 2): -0.18871731336850317,
 ((2, 3, 3), 3): -0.2360800945695969,
 ((2, 3, 3), 4): 0.725511420725562,
 ((5, 2, 0), 1): -0.4891231375430447,
 ((5, 2, 0), 2): 0.08198039370442523,
 ((5, 2, 0), 3): -0.19271821201869876,
 ((5, 2, 0), 4): -0.13608262963703943,
 ((0, 1, 3), 1): 0.0,
 ((0, 1, 3), 2): 0.0,
 ((0, 1, 3), 3): 0.0,
 ((0, 1, 3), 4): 0.0,
 ((1, 3, 3), 1): 0.6220429336477444,
 ((1, 3, 3), 2): 0.3996041115233213,
 ((1, 3, 3), 3): 0.566894305494837,
 ((1, 3, 3), 4): 0.09922591404068637,
 ((5, 3, 0), 1): 0.859185107989072,
 ((5, 3, 0), 2): 0.15678768840967106,
 ((5, 3, 0), 3): 0.018591507455134604,
 ((5, 3, 0), 4): 0.1592348914009305,
 ((1, 3, 2), 1): 0.052213364360472525,
 ((1, 3, 2), 2): 0.1039162302280836,
 ((1, 3, 2), 3): -0.06074542371268343,
 ((1, 3, 2), 4): 0.09244882990423431,
 ((0, 2, 3), 1): 0.00732143294086729,
 ((0, 2, 3), 2): 0.16305959896304145,
 ((0, 2, 3), 3): -0.1412757468180157,
 ((0, 2, 3), 4): -0.08711889658017835,
 ((3, 0, 3), 1): 0.13760104453522848,
 ((3, 0, 3), 2): 0.10572564473435664,
 ((3, 0, 3), 3): 0.15976458248202974,
 ((3, 0, 3), 4): 0.16778355098539288,
 ((4, 0, 3), 1): 0.0,
 ((4, 0, 3), 2): 0.0,
 ((4, 0, 3), 3): 0.0,
 ((4, 0, 3), 4): 0.0,
 ((0, 0, 2), 1): 0.0909631749648856,
 ((0, 0, 2), 2): -0.2569059747550897,
 ((0, 0, 2), 3): 0.052346132746316165,
 ((0, 0, 2), 4): 0.2239247192819862,
 ((0, 1, 1), 1): 0.0,
 ((0, 1, 1), 2): 0.0,
 ((0, 1, 1), 3): 0.0,
 ((0, 1, 1), 4): 0.0,
 ((2, 0, 3), 1): 0.05039209211687723,
 ((2, 0, 3), 2): -0.33810454311365223,
 ((2, 0, 3), 3): 0.22867617694248388,
 ((2, 0, 3), 4): -0.7776876921953004,
 ((4, 2, 1), 1): 0.11041181542189804,
 ((4, 2, 1), 2): -0.21865367913814016,
 ((4, 2, 1), 3): 0.24539663643959564,
 ((4, 2, 1), 4): 0.0009660050067443748,
 ((1, 0, 2), 1): -0.8927659984718481,
 ((1, 0, 2), 2): 0.5955066591819742,
 ((1, 0, 2), 3): 0.3569707325645748,
 ((1, 0, 2), 4): -0.047718884055220734,
 ((3, 1, 1), 1): 0.03831380187919553,
 ((3, 1, 1), 2): 1.2891248297412163,
 ((3, 1, 1), 3): 1.6642506014877085,
 ((3, 1, 1), 4): 0.31455292453700956,
 ((4, 1, 1), 1): 0.0,
 ((4, 1, 1), 2): 0.0,
 ((4, 1, 1), 3): 0.0,
 ((4, 1, 1), 4): 0.0,
 ((4, 2, 2), 1): 0.0,
 ((4, 2, 2), 2): 0.0,
 ((4, 2, 2), 3): 0.0,
 ((4, 2, 2), 4): 0.0,
 ((3, 2, 0), 1): -0.21017211762976196,
 ((3, 2, 0), 2): -0.09679134241647969,
 ((3, 2, 0), 3): 0.056826311508412886,
 ((3, 2, 0), 4): 0.0685592899444547,
 ((3, 1, 0), 1): -0.2965225413566426,
 ((3, 1, 0), 2): -0.00036753548140833203,
 ((3, 1, 0), 3): -0.024750980514261833,
 ((3, 1, 0), 4): 0.14927486687739933,
 ((0, 2, 0), 1): -0.22616440603793642,
 ((0, 2, 0), 2): -0.005933449873309904,
 ((0, 2, 0), 3): 0.054007999825660846,
 ((0, 2, 0), 4): -0.11701329721208875}

## 6) Minimum-distance (MD) fit of cost parameters

The HM moment says \textbf{empirical log-odds} must equal $(- \text{expected cost}) + \beta \times \text{CCS difference}.$

With latent types $L$, expected cost is $\textbf{mixture-weighted}$: $\sum_L \pi_L \big(k_0 + k_L + \varphi_L a \big).$

In [36]:
a_mids = np.array([0.5*(a_cuts[b]+a_cuts[b+1]) for b in range(len(a_cuts)-1)], float)

def objective(theta):
    k0, kL_low, kL_high, phi_low, phi_high, pi_low = theta
    pi=np.array([pi_low, max(1e-6, 1.0-pi_low)]); pi=pi/np.sum(pi)
    loss=0.0; wsum=0.0
    for s in states:
        ia,iy,iage = s
        P = ccp[s]
        a_mid = a_mids[ia]
        costs = np.array([k0 + kL_low + phi_low*a_mid, k0 + kL_high + phi_high*a_mid])
        exp_cost = float(np.sum(pi * costs))
        for j in range(1,J):
            logodds = float(np.log(P[j]) - np.log(P[0]))
            lam = -exp_cost + BETA * delta_cache[(s,j)]
            w = max(state_counts.get(s,1.0), 1.0)
            loss += (logodds - lam)**2 * w
            wsum += w
    return loss / max(wsum,1.0)

theta0 = np.array([20.0, 20.0, 5.0, 0.01, 0.005, 0.5], float)
rng = np.random.default_rng(0)
best_theta = theta0.copy(); best_val = objective(best_theta)
for it in range(200):
    cand = best_theta + rng.normal(0, [2,2,2,0.001,0.001,0.05], size=6)
    val = objective(cand)
    if val < best_val:
        best_theta, best_val = cand, val
best_val, best_theta

(7.9771916031685945,
 array([ 2.62685042e-01,  2.99549541e+01, -1.21102124e+00, -3.28823248e-03,
         7.04896717e-04,  2.12771239e-01]))

## 7) EM: infer laten literacy (personal level)

The HM moment says \textbf{empirical log-odds} must equal $(- \text{expected cost}) + \beta \times \text{CCS difference}.$

With latent types $L$, expected cost is $\textbf{mixture-weighted}$: $\sum_L \pi_L \big(k_0 + k_L + \varphi_L a \big).$

In [37]:
def type_ccp(theta):
    k0, kL_low, kL_high, phi_low, phi_high, pi_low = theta
    def ccps_at_state(s, L):
        ia,_,_ = s
        a_mid = a_mids[ia]
        if L==0:
            kL, phi = kL_low, phi_low
        else:
            kL, phi = kL_high, phi_high
        lam = np.zeros(J); lam[0]=0.0
        for j in range(1,J):
            lam[j] = - (k0 + kL + phi*a_mid) + BETA * delta_cache[(s,j)]
        return softmax(lam)
    return ccps_at_state

traj = defaultdict(list)
for _, row in dfb.sort_values(['id','t']).iterrows():
    s_t = (int(row['ia']), int(row['iy']), int(row['iage']))
    j_t = int(row['j'])
    traj[int(row['id'])].append((s_t, j_t))

def em(theta_init, n_iter=2):
    theta = theta_init.copy()
    k0, kL_low, kL_high, phi_low, phi_high, pi_low = theta
    pi = np.array([pi_low, max(1e-6, 1.0-pi_low)]); pi = pi/np.sum(pi)
    for it in range(n_iter):
        ccps = type_ccp(theta)
        omega={}
        for pid, seq in traj.items():
            like=np.zeros(2)
            for L in [0,1]:
                ll=0.0
                for (s_t, j_t) in seq:
                    P = ccps(s_t, L)
                    ll += np.log(max(P[j_t], 1e-12))
                like[L]=np.exp(ll)
            post = pi * like
            s = post.sum()
            omega[pid] = post/s if s>0 else np.array([0.5,0.5])
        # update pi
        mat = np.stack(list(omega.values()))
        pi = mat.mean(axis=0); pi = pi/np.sum(pi)
        # small local search to re-fit costs keeping pi fixed
        def objective_fixed_pi(th):
            th = th.copy()
            th[-1] = pi[0]
            return objective(th)
        best = theta.copy(); best[-1] = pi[0]
        best_val = objective(best)
        for _ in range(100):
            cand = best + np.random.normal(0, [1,1,1,0.0005,0.0005,0.0], size=6)
            val = objective_fixed_pi(cand)
            if val < best_val:
                best, best_val = cand, val
        theta = best; theta[-1] = pi[0]
    return theta, pi, omega

theta_em, pi_em, omega = em(best_theta, n_iter=2)
theta_em, pi_em

(array([ 2.28360209e+00,  2.45559269e+01, -5.25377955e+00,  1.67598934e-03,
        -1.09009610e-03,  3.13153807e-01]),
 array([0.31315381, 0.68684619]))

In [38]:
rows=[]
for pid, post in omega.items():
    rows.append({'id':pid, 'p_low': float(post[0]), 'p_high': float(post[1])})
post_df = pd.DataFrame(rows).sort_values('id').reset_index(drop=True)
post_df.head()

   id         p_low        p_high
0   0  4.993220e-17  1.000000e+00
1   1  2.415025e-05  9.999758e-01
2   2  1.379811e-18  1.000000e+00
3   3  9.999998e-01  2.392811e-07
4   4  2.470785e-25  1.000000e+00

In [40]:
post_df

      id         p_low        p_high
0      0  4.993220e-17  1.000000e+00
1      1  2.415025e-05  9.999758e-01
2      2  1.379811e-18  1.000000e+00
3      3  9.999998e-01  2.392811e-07
4      4  2.470785e-25  1.000000e+00
..   ...           ...           ...
145  145  1.000000e+00  1.975523e-17
146  146  1.160922e-06  9.999988e-01
147  147  1.280283e-25  1.000000e+00
148  148  4.552796e-05  9.999545e-01
149  149  5.893743e-07  9.999994e-01

[150 rows x 3 columns]

In [39]:
summary = {
    'theta_em': list(map(float, theta_em)),
    'pi_em': list(map(float, pi_em)),
    'objective_value': float(objective(theta_em))
}
print(json.dumps(summary, indent=2))

{
  "theta_em": [
    2.2836020913409785,
    24.55592686094956,
    -5.253779547820741,
    0.001675989344067632,
    -0.001090096102197233,
    0.3131538070310215
  ],
  "pi_em": [
    0.3131538070310215,
    0.6868461929689785
  ],
  "objective_value": 6.6061390116660865
}