# CCP Literacy Estimation — Step-by-Step Demo (Model 1)

This notebook shows CCP estimation, transitions, CCS, a small MD fit, and a light EM loop.

In [1]:
import numpy as np, pandas as pd, json
from collections import defaultdict

CSV_PATH = 'simulated_panel.csv'
BETA=0.96
X_GRID = np.array([0.0,0.25,0.5,0.75,1.0])
J=len(X_GRID)
A_BINS,Y_BINS,AGE_BINS=6,4,4
ALPHA=5.0
H,DRAWS=3,30
K_TYPES=2
EULER_GAMMA=0.5772156649015329

## 1) Load the panel data

**Why**: We need a person–time panel with $(a,y,age,x)$ to build states and choices.

In [2]:
df = pd.read_csv(CSV_PATH)
df.head()

   id  t             a        y     x   age     s             c  type
0   1  0  51882.159995  25000.0  0.00  30.0  0.80  15583.960639     2
1   1  1  62335.842556  25000.0  0.25  31.0  0.80  14179.793847     2
2   1  2  56719.175390  25000.0  1.00  32.0  0.80  11954.547584     2
3   1  3  47818.190334  25000.0  0.25  33.0  0.60  23211.704425     2
4   1  4  34817.556638  25000.0  0.25  34.0  0.95   2255.859542     2

## 2) Define state bins and discretize actions

- CCPs and transitions are nonparametric objects. To estimate them robustly, we need a finite state grid. Quantile bins give balanced cells.
- A discrete action set $J=\{0,0.25,0.5,0.75,1\}$ makes logit CCPs tractable and aligns with Hotz–Miller.

In [3]:
def quantile_bins(series, nbins):
    qs = np.linspace(0,1,nbins+1)
    cuts = series.quantile(qs).values.astype(float)
    for i in range(1,len(cuts)):
        if cuts[i] <= cuts[i-1]:
            cuts[i] = cuts[i-1] + 1e-9
    return cuts

def cut_to_bins(x, cuts):
    return int(np.clip(np.searchsorted(cuts, x, side='right')-1, 0, len(cuts)-2))

def dirichlet_smooth(counts, alpha=5.0):
    counts = np.asarray(counts,float)
    prior = alpha/len(counts)
    return (counts + prior)/(counts.sum()+alpha)

def inclusive_value_from_ccp(P):
    P = np.clip(np.asarray(P,float), 1e-12,1-1e-12)
    return -float(np.log(P[0]))

def softmax(v):
    v = np.asarray(v,float); v = v - np.max(v)
    ex = np.exp(v); return ex/ex.sum()

In [4]:
a_cuts = quantile_bins(df['a'], A_BINS)
y_cuts = quantile_bins(df['y'], Y_BINS)
age_cuts = quantile_bins(df['age'], AGE_BINS)

dfb = df.copy()
dfb['ia'] = dfb['a'].apply(lambda v: cut_to_bins(v, a_cuts))
dfb['iy'] = dfb['y'].apply(lambda v: cut_to_bins(v, y_cuts))
dfb['iage'] = dfb['age'].apply(lambda v: cut_to_bins(v, age_cuts))

def x_to_j(x): 
    return int(np.argmin(np.abs(X_GRID - float(x))))

dfb['j'] = dfb['x'].apply(x_to_j)

dfb = dfb.sort_values(['id','t']).reset_index(drop=True)

for col in ['ia','iy','iage','j']:
    dfb[col+'_next'] = dfb.groupby('id')[col].shift(-1)

dfb = dfb.dropna(subset=['ia_next','iy_next','iage_next']).copy()

for col in ['ia_next','iy_next','iage_next','j_next']:
    dfb[col] = dfb[col].astype(int)

dfb.head()

,id,t,a,y,x,age,s,c,type,ia,iy,iage,j,ia_next,iy_next,iage_next,j_next
0,1,0,51882.159995,25000.0,0.00,30.0,0.80,15583.960639,2,3,0,0,0,4,0,0,1
1,1,1,62335.842556,25000.0,0.25,31.0,0.80,14179.793847,2,4,0,0,1,4,0,1,4
2,1,2,56719.175390,25000.0,1.00,32.0,0.80,11954.547584,2,4,0,1,4,3,0,1,1
3,1,3,47818.190334,25000.0,0.25,33.0,0.60,23211.704425,2,3,0,1,1,1,0,2,1
4,1,4,34817.556638,25000.0,0.25,34.0,0.95,2255.859542,2,1,0,2,1,2,0,2,3

## 3) Estimate CCP $\hat{P}(j \mid s)$

With logit shocks, CCPs invert to value-index differences and yield an inclusive value for the state. They are the data bridge to dynamic values.

In [272]:
J=len(X_GRID)
counts = defaultdict(lambda: np.zeros(J, float))

for _,row in dfb.iterrows():
    s=(int(row['ia']), int(row['iy']), int(row['iage']))
    j=int(row['j'])
    counts[s][j]+=1.0

ccp={}; state_counts={}

for s,cvec in counts.items():
    state_counts[s]=float(cvec.sum())
    ccp[s]=dirichlet_smooth(cvec, alpha=ALPHA)
len(ccp)

24

In [273]:
counts

defaultdict(<function __main__.<lambda>()>,
            {(3, 0, 0): array([29., 33., 30., 22., 34.]),
             (4, 0, 0): array([36., 36., 39., 38., 47.]),
             (4, 0, 1): array([36., 47., 23., 40., 40.]),
             (3, 0, 1): array([46., 38., 41., 41., 41.]),
             (1, 0, 2): array([39., 41., 46., 47., 35.]),
             (2, 0, 2): array([44., 52., 39., 53., 37.]),
             (3, 0, 3): array([27., 17., 30., 25., 21.]),
             (5, 0, 0): array([34., 53., 45., 49., 53.]),
             (5, 0, 1): array([45., 34., 44., 28., 44.]),
             (5, 0, 2): array([31., 37., 45., 40., 39.]),
             (5, 0, 3): array([22., 14., 12., 18., 16.]),
             (4, 0, 2): array([40., 45., 45., 33., 48.]),
             (4, 0, 3): array([24., 18., 23., 24., 23.]),
             (0, 0, 0): array([65., 67., 67., 72., 72.]),
             (1, 0, 1): array([34., 52., 52., 41., 42.]),
             (2, 0, 1): array([38., 52., 33., 34., 50.]),
             (2, 0, 0): array([31., 26., 30., 25., 21.]),
             (0, 0, 1): array([42., 43., 30., 37., 32.]),
             (0, 0, 3): array([ 8., 13., 16., 12., 21.]),
             (1, 0, 3): array([22., 27., 16., 14., 22.]),
             (3, 0, 2): array([41., 56., 46., 33., 44.]),
             (2, 0, 3): array([28., 21., 22., 23., 21.]),
             (1, 0, 0): array([34., 28., 22., 34., 28.]),
             (0, 0, 2): array([25., 34., 22., 33., 30.])})

In [274]:
ccp

{(3,
  0,
  0): array([0.19607843, 0.22222222, 0.20261438, 0.1503268 , 0.22875817]),
 (4,
  0,
  0): array([0.1840796 , 0.1840796 , 0.19900498, 0.19402985, 0.23880597]),
 (4,
  0,
  1): array([0.19371728, 0.2513089 , 0.12565445, 0.21465969, 0.21465969]),
 (3,
  0,
  1): array([0.22169811, 0.18396226, 0.19811321, 0.19811321, 0.19811321]),
 (1,
  0,
  2): array([0.18779343, 0.1971831 , 0.22065728, 0.22535211, 0.16901408]),
 (2,
  0,
  2): array([0.19565217, 0.23043478, 0.17391304, 0.23478261, 0.16521739]),
 (3, 0, 3): array([0.224, 0.144, 0.248, 0.208, 0.176]),
 (5,
  0,
  0): array([0.14644351, 0.22594142, 0.19246862, 0.20920502, 0.22594142]),
 (5, 0, 1): array([0.23 , 0.175, 0.225, 0.145, 0.225]),
 (5,
  0,
  2): array([0.16243655, 0.1928934 , 0.23350254, 0.20812183, 0.20304569]),
 (5,
  0,
  3): array([0.26436782, 0.17241379, 0.14942529, 0.2183908 , 0.1954023 ]),
 (4,
  0,
  2): array([0.18981481, 0.21296296, 0.21296296, 0.15740741, 0.22685185]),
 (4,
  0,
  3): array([0.21367521, 0.16239316, 0.20512821, 0.21367521, 0.20512821]),
 (0,
  0,
  0): array([0.18965517, 0.1954023 , 0.1954023 , 0.20977011, 0.20977011]),
 (1,
  0,
  1): array([0.15486726, 0.23451327, 0.23451327, 0.18584071, 0.19026549]),
 (2,
  0,
  1): array([0.18396226, 0.25      , 0.16037736, 0.16509434, 0.24056604]),
 (2,
  0,
  0): array([0.23188406, 0.19565217, 0.22463768, 0.1884058 , 0.15942029]),
 (0,
  0,
  1): array([0.22751323, 0.23280423, 0.16402116, 0.2010582 , 0.17460317]),
 (0,
  0,
  3): array([0.12      , 0.18666667, 0.22666667, 0.17333333, 0.29333333]),
 (1,
  0,
  3): array([0.21698113, 0.26415094, 0.16037736, 0.14150943, 0.21698113]),
 (3,
  0,
  2): array([0.18666667, 0.25333333, 0.20888889, 0.15111111, 0.2       ]),
 (2,
  0,
  3): array([0.24166667, 0.18333333, 0.19166667, 0.2       , 0.18333333]),
 (1,
  0,
  0): array([0.23178808, 0.19205298, 0.15231788, 0.23178808, 0.19205298]),
 (0,
  0,
  2): array([0.17449664, 0.23489933, 0.15436242, 0.22818792, 0.20805369])}

## 4) Estimate transitions $\hat{p}(s' \mid s,j)$

To compute the continuation under “what if I choos $j$ now?”, we must know how states move given current state+action. We estimate it empirically from the panel.

In [275]:
trans = defaultdict(lambda: defaultdict(float))

for _, row in dfb.iterrows():
    s=(int(row['ia']), int(row['iy']), int(row['iage']))
    j=int(row['j'])
    sp=(int(row['ia_next']), int(row['iy_next']), int(row['iage_next']))
    trans[(s,j)][sp]+=1.0

trans_prob={}
for key,d in trans.items():
    items=list(d.items())
    probs=np.array([v for (_,v) in items], float); probs=probs/probs.sum()
    trans_prob[key]=([sp for (sp,_) in items], probs)

def draw_next_state(s,j):
    key=(s,j)
    if key not in trans_prob:
        cand=[(k,v) for (k,v) in trans_prob.items() if k[0]==s]
        if not cand:
            return s
        sps=[]; ps=[]
        for (_, (sp_list, p_list)) in cand:
            sps+=sp_list; ps+=list(p_list/len(cand))
        ps=np.array(ps,float); ps=ps/ps.sum()
        idx=np.random.choice(len(sps), p=ps)
        return sps[idx]
    sps,ps=trans_prob[key]
    idx=np.random.choice(len(sps), p=ps)
    return sps[idx]

In [276]:
trans_prob

{((3, 0, 0),
  0): ([(4, 0, 0),
   (5, 0, 0),
   (2, 0, 1),
   (5, 0, 1),
   (4, 0, 1),
   (3, 0, 0),
   (2, 0, 0),
   (3,
    0,
    1)], array([0.31034483, 0.20689655, 0.13793103, 0.13793103, 0.10344828,
         0.03448276, 0.03448276, 0.03448276])),
 ((4, 0, 0),
  1): ([(4, 0, 1),
   (5, 0, 1),
   (3, 0, 1),
   (4, 0, 0),
   (2, 0, 1),
   (3, 0, 0),
   (2, 0, 0),
   (5,
    0,
    0)], array([0.27777778, 0.13888889, 0.08333333, 0.19444444, 0.08333333,
         0.05555556, 0.11111111, 0.05555556])),
 ((4, 0, 1),
  4): ([(3, 0, 1),
   (2, 0, 2),
   (1, 0, 2),
   (4, 0, 2),
   (1, 0, 1),
   (5, 0, 2),
   (3, 0, 2),
   (5, 0, 1),
   (2, 0, 1),
   (4,
    0,
    1)], array([0.1  , 0.1  , 0.075, 0.15 , 0.1  , 0.05 , 0.075, 0.075, 0.125,
         0.15 ])),
 ((3, 0, 1),
  1): ([(1, 0, 2),
   (3, 0, 1),
   (4, 0, 2),
   (3, 0, 2),
   (1, 0, 1),
   (0, 0, 1),
   (4, 0, 1),
   (2,
    0,
    1)], array([0.18421053, 0.13157895, 0.21052632, 0.18421053, 0.13157895,
         0.02631579, 0.10526316, 0.02631579])),
 ((1, 0, 2),
  1): ([(2, 0, 2),
   (3, 0, 2),
   (0, 0, 2),
   (2, 0, 3),
   (1, 0, 2),
   (0, 0, 3),
   (3, 0, 3),
   (1,
    0,
    3)], array([0.2195122 , 0.17073171, 0.17073171, 0.07317073, 0.09756098,
         0.12195122, 0.12195122, 0.02439024])),
 ((2, 0, 2),
  3): ([(3, 0, 3),
   (4, 0, 3),
   (0, 0, 2),
   (0, 0, 3),
   (2, 0, 2),
   (4, 0, 2),
   (3, 0, 2),
   (2, 0, 3),
   (1, 0, 3),
   (1,
    0,
    2)], array([0.0754717 , 0.09433962, 0.0754717 , 0.0754717 , 0.09433962,
         0.09433962, 0.18867925, 0.09433962, 0.11320755, 0.09433962])),
 ((3, 0, 3),
  3): ([(3, 0, 3),
   (1, 0, 3),
   (4, 0, 3),
   (2, 0, 3),
   (0, 0, 3),
   (5, 0, 3)], array([0.24, 0.28, 0.24, 0.16, 0.04, 0.04])),
 ((5, 0, 0),
  4): ([(4, 0, 0),
   (3, 0, 0),
   (4, 0, 1),
   (5, 0, 1),
   (5, 0, 0),
   (1, 0, 1),
   (2, 0, 0),
   (3, 0, 1),
   (2,
    0,
    1)], array([0.11320755, 0.09433962, 0.13207547, 0.26415094, 0.18867925,
         0.05660377, 0.09433962, 0.03773585, 0.01886792])),
 ((5, 0, 1),
  3): ([(4, 0, 1),
   (4, 0, 2),
   (5, 0, 2),
   (5, 0, 1),
   (3, 0, 2),
   (3,
    0,
    1)], array([0.17857143, 0.28571429, 0.32142857, 0.10714286, 0.03571429,
         0.07142857])),
 ((4, 0, 1),
  1): ([(5, 0, 2),
   (1, 0, 1),
   (2, 0, 2),
   (1, 0, 2),
   (2, 0, 1),
   (4, 0, 2),
   (3, 0, 1),
   (4, 0, 1),
   (5, 0, 1),
   (3,
    0,
    2)], array([0.04255319, 0.14893617, 0.14893617, 0.06382979, 0.06382979,
         0.25531915, 0.04255319, 0.12765957, 0.08510638, 0.0212766 ])),
 ((5, 0, 2),
  2): ([(5, 0, 2),
   (4, 0, 3),
   (2, 0, 2),
   (3, 0, 2),
   (3, 0, 3),
   (2, 0, 3),
   (5, 0, 3),
   (4,
    0,
    2)], array([0.35555556, 0.13333333, 0.13333333, 0.11111111, 0.04444444,
         0.04444444, 0.11111111, 0.06666667])),
 ((5, 0, 2),
  4): ([(5, 0, 3),
   (4, 0, 3),
   (5, 0, 2),
   (3, 0, 3),
   (1, 0, 2),
   (2, 0, 3),
   (4, 0, 2),
   (2, 0, 2),
   (3, 0, 2),
   (1,
    0,
    3)], array([0.28205128, 0.20512821, 0.12820513, 0.02564103, 0.02564103,
         0.05128205, 0.12820513, 0.07692308, 0.05128205, 0.02564103])),
 ((5, 0, 3), 4): ([(5, 0, 3), (2, 0, 3), (4, 0, 3), (3, 0, 3), (1, 0, 3)],
  array([0.3125, 0.25  , 0.25  , 0.125 , 0.0625])),
 ((4, 0, 0),
  0): ([(5, 0, 0),
   (3, 0, 1),
   (5, 0, 1),
   (3, 0, 0),
   (4, 0, 1),
   (4,
    0,
    0)], array([0.47222222, 0.08333333, 0.25      , 0.08333333, 0.05555556,
         0.05555556])),
 ((5, 0, 0), 0): ([(5, 0, 1), (5, 0, 0), (4, 0, 0), (4, 0, 1)],
  array([0.26470588, 0.32352941, 0.29411765, 0.11764706])),
 ((5, 0, 1),
  4): ([(5, 0, 1),
   (2, 0, 2),
   (2, 0, 1),
   (5, 0, 2),
   (4, 0, 2),
   (4, 0, 1),
   (1, 0, 1),
   (3, 0, 1),
   (3,
    0,
    2)], array([0.40909091, 0.09090909, 0.02272727, 0.15909091, 0.11363636,
         0.06818182, 0.02272727, 0.04545455, 0.06818182])),
 ((4, 0, 2),
  0): ([(5, 0, 2),
   (5, 0, 3),
   (3, 0, 3),
   (4, 0, 3),
   (3, 0, 2),
   (4, 0, 2)], array([0.25 , 0.225, 0.225, 0.05 , 0.225, 0.025])),
 ((4, 0, 3), 3): ([(1, 0, 3), (5, 0, 3), (2, 0, 3), (4, 0, 3), (3, 0, 3)],
  array([0.08333333, 0.16666667, 0.16666667, 0.20833333, 0.375     ])),
 ((0, 0, 0),
  4): ([(0, 0, 0),
   (1, 0, 0),
   (0, 0, 1),
   (1, 0, 1),
   (2, 0, 1),
   (2, 0, 0),
   (3,
    0,
    1)], array([0.43055556, 0.13888889, 0.22222222, 0.08333333, 0.08333333,
         0.02777778, 0.01388889])),
 ((0, 0, 0),
  2): ([(1, 0, 1),
   (0, 0, 0),
   (0, 0, 1),
   (1, 0, 0),
   (2, 0, 1),
   (2,
    0,
    0)], array([0.17910448, 0.37313433, 0.28358209, 0.11940299, 0.01492537,
         0.02985075])),
 ((1, 0, 1),
  4): ([(2, 0, 1),
   (0, 0, 1),
   (4, 0, 2),
   (2, 0, 2),
   (0, 0, 2),
   (3, 0, 1),
   (1, 0, 1),
   (3, 0, 2),
   (1, 0, 2),
   (4,
    0,
    1)], array([0.04761905, 0.26190476, 0.04761905, 0.16666667, 0.14285714,
         0.0952381 , 0.02380952, 0.0952381 , 0.0952381 , 0.02380952])),
 ((2, 0, 1),
  2): ([(1, 0, 2),
   (2, 0, 2),
   (2, 0, 1),
   (0, 0, 2),
   (0, 0, 1),
   (1, 0, 1),
   (4, 0, 1),
   (4, 0, 2),
   (3, 0, 1),
   (3,
    0,
    2)], array([0.15151515, 0.12121212, 0.15151515, 0.06060606, 0.09090909,
         0.09090909, 0.09090909, 0.09090909, 0.06060606, 0.09090909])),
 ((1, 0, 2),
  3): ([(2, 0, 2),
   (2, 0, 3),
   (1, 0, 3),
   (3, 0, 2),
   (3, 0, 3),
   (0, 0, 3),
   (4, 0, 3),
   (1, 0, 2),
   (0, 0, 2),
   (4,
    0,
    2)], array([0.23404255, 0.12765957, 0.14893617, 0.08510638, 0.08510638,
         0.12765957, 0.0212766 , 0.06382979, 0.08510638, 0.0212766 ])),
 ((4, 0, 3), 0): ([(5, 0, 3), (3, 0, 3), (4, 0, 3)],
  array([0.75      , 0.16666667, 0.08333333])),
 ((0, 0, 0),
  3): ([(2, 0, 0),
   (0, 0, 0),
   (1, 0, 1),
   (0, 0, 1),
   (1, 0, 0),
   (3,
    0,
    0)], array([0.09722222, 0.43055556, 0.13888889, 0.18055556, 0.13888889,
         0.01388889])),
 ((2, 0, 0),
  2): ([(0, 0, 1),
   (1, 0, 1),
   (4, 0, 0),
   (3, 0, 0),
   (2, 0, 0),
   (4, 0, 1),
   (2, 0, 1),
   (3, 0, 1),
   (1,
    0,
    0)], array([0.13333333, 0.13333333, 0.03333333, 0.2       , 0.06666667,
         0.06666667, 0.2       , 0.13333333, 0.03333333])),
 ((0, 0, 1),
  3): ([(0, 0, 1),
   (1, 0, 2),
   (1, 0, 1),
   (2, 0, 1),
   (0, 0, 2),
   (3, 0, 1),
   (2, 0, 2),
   (3,
    0,
    2)], array([0.21621622, 0.21621622, 0.24324324, 0.08108108, 0.13513514,
         0.02702703, 0.05405405, 0.02702703])),
 ((2, 0, 2),
  2): ([(0, 0, 3),
   (0, 0, 2),
   (3, 0, 2),
   (1, 0, 3),
   (4, 0, 2),
   (2, 0, 3),
   (1, 0, 2),
   (2, 0, 2),
   (3, 0, 3),
   (4,
    0,
    3)], array([0.05128205, 0.02564103, 0.20512821, 0.17948718, 0.07692308,
         0.12820513, 0.12820513, 0.12820513, 0.02564103, 0.05128205])),
 ((0, 0, 3), 2): ([(1, 0, 3), (2, 0, 3), (0, 0, 3), (3, 0, 3)],
  array([0.75  , 0.0625, 0.125 , 0.0625])),
 ((5, 0, 0),
  2): ([(2, 0, 0),
   (5, 0, 0),
   (3, 0, 1),
   (3, 0, 0),
   (4, 0, 0),
   (4, 0, 1),
   (5,
    0,
    1)], array([0.04444444, 0.26666667, 0.08888889, 0.17777778, 0.11111111,
         0.08888889, 0.22222222])),
 ((2, 0, 0),
  4): ([(3, 0, 1),
   (2, 0, 1),
   (0, 0, 0),
   (1, 0, 0),
   (1, 0, 1),
   (2, 0, 0),
   (3, 0, 0),
   (4, 0, 1),
   (4, 0, 0),
   (5, 0, 0),
   (0,
    0,
    1)], array([0.28571429, 0.14285714, 0.04761905, 0.04761905, 0.14285714,
         0.0952381 , 0.04761905, 0.04761905, 0.04761905, 0.04761905,
         0.04761905])),
 ((3, 0, 1),
  4): ([(4, 0, 2),
   (2, 0, 1),
   (3, 0, 2),
   (3, 0, 1),
   (5, 0, 2),
   (4, 0, 1),
   (0, 0, 2),
   (1, 0, 1),
   (0, 0, 1),
   (1, 0, 2),
   (2, 0, 2),
   (5,
    0,
    1)], array([0.04878049, 0.12195122, 0.09756098, 0.17073171, 0.09756098,
         0.12195122, 0.02439024, 0.12195122, 0.02439024, 0.04878049,
         0.09756098, 0.02439024])),
 ((4, 0, 2),
  2): ([(4, 0, 2),
   (3, 0, 3),
   (2, 0, 3),
   (5, 0, 3),
   (3, 0, 2),
   (4, 0, 3),
   (1, 0, 2),
   (1, 0, 3),
   (2, 0, 2),
   (5,
    0,
    2)], array([0.22222222, 0.08888889, 0.08888889, 0.13333333, 0.08888889,
         0.15555556, 0.04444444, 0.06666667, 0.06666667, 0.04444444])),
 ((4, 0, 2),
  3): ([(1, 0, 3),
   (2, 0, 3),
   (3, 0, 3),
   (2, 0, 2),
   (1, 0, 2),
   (4, 0, 2),
   (3, 0, 2),
   (5, 0, 3),
   (5, 0, 2),
   (4,
    0,
    3)], array([0.09090909, 0.12121212, 0.15151515, 0.12121212, 0.12121212,
         0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.03030303])),
 ((1, 0, 3), 0): ([(4, 0, 3), (3, 0, 3), (1, 0, 3)],
  array([0.31818182, 0.27272727, 0.40909091])),
 ((0, 0, 0),
  1): ([(0, 0, 1),
   (1, 0, 0),
   (0, 0, 0),
   (1, 0, 1),
   (2, 0, 0),
   (2,
    0,
    1)], array([0.26865672, 0.11940299, 0.37313433, 0.13432836, 0.04477612,
         0.05970149])),
 ((0, 0, 1),
  1): ([(0, 0, 1),
   (2, 0, 1),
   (2, 0, 2),
   (1, 0, 2),
   (0, 0, 2),
   (1,
    0,
    1)], array([0.25581395, 0.09302326, 0.11627907, 0.13953488, 0.18604651,
         0.20930233])),
 ((1, 0, 2),
  0): ([(1, 0, 2),
   (4, 0, 2),
   (3, 0, 2),
   (1, 0, 3),
   (4, 0, 3),
   (3,
    0,
    3)], array([0.17948718, 0.17948718, 0.1025641 , 0.12820513, 0.15384615,
         0.25641026])),
 ((1, 0, 2),
  4): ([(0, 0, 3),
   (1, 0, 2),
   (1, 0, 3),
   (3, 0, 3),
   (0, 0, 2),
   (4, 0, 2),
   (2, 0, 3),
   (2, 0, 2),
   (3, 0, 2),
   (4,
    0,
    3)], array([0.11428571, 0.17142857, 0.14285714, 0.14285714, 0.08571429,
         0.02857143, 0.08571429, 0.11428571, 0.08571429, 0.02857143])),
 ((0, 0, 3), 1): ([(1, 0, 3), (0, 0, 3), (2, 0, 3)],
  array([0.61538462, 0.23076923, 0.15384615])),
 ((3, 0, 1),
  3): ([(2, 0, 1),
   (1, 0, 2),
   (1, 0, 1),
   (5, 0, 1),
   (2, 0, 2),
   (3, 0, 2),
   (3, 0, 1),
   (0, 0, 2),
   (4, 0, 2),
   (4, 0, 1),
   (5,
    0,
    2)], array([0.12195122, 0.12195122, 0.14634146, 0.02439024, 0.09756098,
         0.17073171, 0.07317073, 0.02439024, 0.14634146, 0.04878049,
         0.02439024])),
 ((2, 0, 1),
  3): ([(3, 0, 2),
   (2, 0, 1),
   (1, 0, 2),
   (5, 0, 2),
   (3, 0, 1),
   (1, 0, 1),
   (4, 0, 2),
   (0, 0, 2),
   (0, 0, 1),
   (2,
    0,
    2)], array([0.17647059, 0.08823529, 0.20588235, 0.02941176, 0.14705882,
         0.11764706, 0.02941176, 0.05882353, 0.08823529, 0.05882353])),
 ((3, 0, 2),
  0): ([(4, 0, 2),
   (5, 0, 2),
   (2, 0, 3),
   (5, 0, 3),
   (2, 0, 2),
   (4, 0, 3),
   (3, 0, 3),
   (3,
    0,
    2)], array([0.17073171, 0.17073171, 0.12195122, 0.2195122 , 0.07317073,
         0.17073171, 0.04878049, 0.02439024])),
 ((2, 0, 3), 4): ([(2, 0, 3), (4, 0, 3), (3, 0, 3), (1, 0, 3), (0, 0, 3)],
  array([0.38095238, 0.0952381 , 0.0952381 , 0.33333333, 0.0952381 ])),
 ((5, 0, 0),
  3): ([(4, 0, 0),
   (5, 0, 0),
   (5, 0, 1),
   (3, 0, 0),
   (4, 0, 1),
   (2, 0, 1),
   (2, 0, 0),
   (3,
    0,
    1)], array([0.14285714, 0.32653061, 0.18367347, 0.12244898, 0.10204082,
         0.02040816, 0.02040816, 0.08163265])),
 ((3, 0, 1),
  2): ([(3, 0, 1),
   (0, 0, 2),
   (2, 0, 2),
   (4, 0, 1),
   (1, 0, 1),
   (1, 0, 2),
   (4, 0, 2),
   (2, 0, 1),
   (5, 0, 2),
   (3,
    0,
    2)], array([0.2195122 , 0.02439024, 0.04878049, 0.09756098, 0.12195122,
         0.12195122, 0.12195122, 0.09756098, 0.04878049, 0.09756098])),
 ((3, 0, 2),
  1): ([(4, 0, 3),
   (4, 0, 2),
   (2, 0, 2),
   (1, 0, 3),
   (1, 0, 2),
   (3, 0, 2),
   (3, 0, 3),
   (2,
    0,
    3)], array([0.16071429, 0.16071429, 0.05357143, 0.17857143, 0.16071429,
         0.17857143, 0.07142857, 0.03571429])),
 ((4, 0, 3), 2): ([(2, 0, 3), (3, 0, 3), (4, 0, 3), (1, 0, 3), (5, 0, 3)],
  array([0.30434783, 0.2173913 , 0.34782609, 0.08695652, 0.04347826])),
 ((2, 0, 0),
  1): ([(1, 0, 0),
   (3, 0, 1),
   (3, 0, 0),
   (4, 0, 0),
   (1, 0, 1),
   (0, 0, 1),
   (2, 0, 1),
   (0, 0, 0),
   (4, 0, 1),
   (2,
    0,
    0)], array([0.15384615, 0.15384615, 0.23076923, 0.07692308, 0.03846154,
         0.07692308, 0.11538462, 0.03846154, 0.07692308, 0.03846154])),
 ((1, 0, 0), 0): ([(3, 0, 1), (1, 0, 1), (4, 0, 0), (1, 0, 0), (4, 0, 1)],
  array([0.32352941, 0.23529412, 0.29411765, 0.08823529, 0.05882353])),
 ((2, 0, 1),
  0): ([(3, 0, 2),
   (2, 0, 2),
   (4, 0, 1),
   (3, 0, 1),
   (2, 0, 1),
   (5, 0, 1),
   (4, 0, 2),
   (5,
    0,
    2)], array([0.05263158, 0.26315789, 0.15789474, 0.05263158, 0.13157895,
         0.13157895, 0.10526316, 0.10526316])),
 ((5, 0, 3), 2): ([(5, 0, 3), (4, 0, 3), (2, 0, 3), (3, 0, 3)],
  array([0.75      , 0.08333333, 0.08333333, 0.08333333])),
 ((3, 0, 1),
  0): ([(5, 0, 1),
   (4, 0, 1),
   (5, 0, 2),
   (3, 0, 2),
   (4, 0, 2),
   (3, 0, 1),
   (2, 0, 1),
   (2,
    0,
    2)], array([0.2173913 , 0.2173913 , 0.2173913 , 0.02173913, 0.15217391,
         0.04347826, 0.04347826, 0.08695652])),
 ((5, 0, 1),
  2): ([(3, 0, 2),
   (5, 0, 1),
   (5, 0, 2),
   (2, 0, 1),
   (4, 0, 2),
   (2, 0, 2),
   (3, 0, 1),
   (4,
    0,
    1)], array([0.13636364, 0.22727273, 0.22727273, 0.06818182, 0.11363636,
         0.09090909, 0.02272727, 0.11363636])),
 ((3, 0, 2),
  4): ([(0, 0, 2),
   (4, 0, 3),
   (5, 0, 3),
   (3, 0, 3),
   (4, 0, 2),
   (2, 0, 3),
   (1, 0, 2),
   (2, 0, 2),
   (1, 0, 3),
   (0, 0, 3),
   (3, 0, 2),
   (5,
    0,
    2)], array([0.06818182, 0.11363636, 0.04545455, 0.11363636, 0.20454545,
         0.15909091, 0.04545455, 0.04545455, 0.09090909, 0.02272727,
         0.06818182, 0.02272727])),
 ((0, 0, 2),
  0): ([(3, 0, 3),
   (2, 0, 3),
   (1, 0, 3),
   (1, 0, 2),
   (2, 0, 2),
   (3, 0, 2),
   (0, 0, 2),
   (4, 0, 3),
   (0, 0, 3)], array([0.04, 0.28, 0.08, 0.12, 0.08, 0.12, 0.12, 0.04, 0.12])),
 ((3, 0, 3),
  4): ([(1, 0, 3),
   (2, 0, 3),
   (0, 0, 3),
   (5, 0, 3),
   (3, 0, 3),
   (4,
    0,
    3)], array([0.14285714, 0.23809524, 0.14285714, 0.14285714, 0.19047619,
         0.14285714])),
 ((1, 0, 0),
  3): ([(0, 0, 1),
   (2, 0, 0),
   (1, 0, 1),
   (1, 0, 0),
   (2, 0, 1),
   (0, 0, 0),
   (3, 0, 1),
   (4, 0, 1),
   (3,
    0,
    0)], array([0.17647059, 0.11764706, 0.05882353, 0.08823529, 0.20588235,
         0.11764706, 0.08823529, 0.02941176, 0.11764706])),
 ((2, 0, 1),
  4): ([(3, 0, 2),
   (3, 0, 1),
   (4, 0, 2),
   (4, 0, 1),
   (1, 0, 1),
   (2, 0, 1),
   (1, 0, 2),
   (2, 0, 2),
   (0, 0, 1),
   (0,
    0,
    2)], array([0.18, 0.12, 0.08, 0.1 , 0.1 , 0.1 , 0.08, 0.1 , 0.1 , 0.04])),
 ((0, 0, 1),
  0): ([(3, 0, 1),
   (2, 0, 1),
   (1, 0, 1),
   (2, 0, 2),
   (0, 0, 1),
   (1, 0, 2),
   (0, 0, 2),
   (4, 0, 1),
   (3,
    0,
    2)], array([0.0952381 , 0.23809524, 0.30952381, 0.07142857, 0.07142857,
         0.04761905, 0.04761905, 0.0952381 , 0.02380952])),
 ((0, 0, 2),
  4): ([(0, 0, 2),
   (1, 0, 3),
   (2, 0, 2),
   (3, 0, 2),
   (1, 0, 2),
   (0, 0, 3),
   (2, 0, 3),
   (3,
    0,
    3)], array([0.3       , 0.1       , 0.03333333, 0.1       , 0.16666667,
         0.2       , 0.06666667, 0.03333333])),
 ((1, 0, 3), 3): ([(0, 0, 3), (2, 0, 3), (1, 0, 3), (3, 0, 3)],
  array([0.42857143, 0.28571429, 0.21428571, 0.07142857])),
 ((2, 0, 1),
  1): ([(3, 0, 2),
   (0, 0, 2),
   (1, 0, 2),
   (4, 0, 1),
   (3, 0, 1),
   (1, 0, 1),
   (2, 0, 2),
   (2, 0, 1),
   (0,
    0,
    1)], array([0.15384615, 0.13461538, 0.15384615, 0.05769231, 0.09615385,
         0.07692308, 0.09615385, 0.15384615, 0.07692308])),
 ((5, 0, 2),
  1): ([(5, 0, 3),
   (2, 0, 3),
   (3, 0, 2),
   (4, 0, 2),
   (3, 0, 3),
   (5, 0, 2),
   (4,
    0,
    3)], array([0.24324324, 0.08108108, 0.02702703, 0.13513514, 0.13513514,
         0.18918919, 0.18918919])),
 ((3, 0, 2),
  2): ([(3, 0, 2),
   (1, 0, 3),
   (3, 0, 3),
   (2, 0, 3),
   (0, 0, 3),
   (4, 0, 3),
   (1, 0, 2),
   (4, 0, 2),
   (2, 0, 2),
   (0,
    0,
    2)], array([0.13043478, 0.15217391, 0.23913043, 0.10869565, 0.02173913,
         0.15217391, 0.04347826, 0.06521739, 0.06521739, 0.02173913])),
 ((1, 0, 3), 2): ([(2, 0, 3), (1, 0, 3), (0, 0, 3), (3, 0, 3)],
  array([0.25  , 0.3125, 0.375 , 0.0625])),
 ((3, 0, 0),
  4): ([(3, 0, 0),
   (4, 0, 1),
   (3, 0, 1),
   (1, 0, 0),
   (5, 0, 0),
   (0, 0, 1),
   (0, 0, 0),
   (2, 0, 0),
   (4, 0, 0),
   (2, 0, 1),
   (1, 0, 1),
   (5,
    0,
    1)], array([0.08823529, 0.23529412, 0.11764706, 0.11764706, 0.08823529,
         0.02941176, 0.02941176, 0.02941176, 0.05882353, 0.08823529,
         0.02941176, 0.08823529])),
 ((3, 0, 0),
  1): ([(1, 0, 1),
   (3, 0, 0),
   (3, 0, 1),
   (1, 0, 0),
   (4, 0, 0),
   (4, 0, 1),
   (5, 0, 0),
   (2, 0, 0),
   (2,
    0,
    1)], array([0.3030303 , 0.15151515, 0.18181818, 0.09090909, 0.12121212,
         0.03030303, 0.06060606, 0.03030303, 0.03030303])),
 ((1, 0, 1),
  0): ([(4, 0, 1),
   (1, 0, 2),
   (1, 0, 1),
   (3, 0, 1),
   (4, 0, 2),
   (2, 0, 2),
   (3,
    0,
    2)], array([0.14705882, 0.23529412, 0.11764706, 0.14705882, 0.17647059,
         0.05882353, 0.11764706])),
 ((2, 0, 3), 1): ([(3, 0, 3), (2, 0, 3), (1, 0, 3), (4, 0, 3), (0, 0, 3)],
  array([0.38095238, 0.38095238, 0.0952381 , 0.0952381 , 0.04761905])),
 ((5, 0, 1), 0): ([(5, 0, 2), (4, 0, 1), (5, 0, 1), (4, 0, 2)],
  array([0.37777778, 0.17777778, 0.4       , 0.04444444])),
 ((5, 0, 2),
  3): ([(4, 0, 2),
   (5, 0, 3),
   (3, 0, 3),
   (2, 0, 2),
   (4, 0, 3),
   (3, 0, 2),
   (2, 0, 3),
   (5,
    0,
    2)], array([0.125, 0.275, 0.125, 0.1  , 0.05 , 0.1  , 0.05 , 0.175])),
 ((3, 0, 3), 1): ([(1, 0, 3), (3, 0, 3), (4, 0, 3), (2, 0, 3)],
  array([0.52941176, 0.11764706, 0.17647059, 0.17647059])),
 ((4, 0, 1),
  0): ([(5, 0, 1),
   (3, 0, 1),
   (5, 0, 2),
   (3, 0, 2),
   (4, 0, 1),
   (4,
    0,
    2)], array([0.30555556, 0.16666667, 0.30555556, 0.16666667, 0.02777778,
         0.02777778])),
 ((5, 0, 1),
  1): ([(3, 0, 2),
   (5, 0, 2),
   (5, 0, 1),
   (3, 0, 1),
   (4, 0, 1),
   (2, 0, 1),
   (2, 0, 2),
   (4,
    0,
    2)], array([0.08823529, 0.35294118, 0.26470588, 0.08823529, 0.02941176,
         0.02941176, 0.02941176, 0.11764706])),
 ((3, 0, 0),
  2): ([(1, 0, 0),
   (4, 0, 0),
   (4, 0, 1),
   (3, 0, 0),
   (1, 0, 1),
   (5, 0, 1),
   (3, 0, 1),
   (2,
    0,
    1)], array([0.1       , 0.1       , 0.2       , 0.1       , 0.3       ,
         0.03333333, 0.13333333, 0.03333333])),
 ((1, 0, 0),
  2): ([(0, 0, 1),
   (3, 0, 0),
   (0, 0, 0),
   (2, 0, 0),
   (1, 0, 1),
   (2, 0, 1),
   (1, 0, 0),
   (3,
    0,
    1)], array([0.22727273, 0.13636364, 0.18181818, 0.09090909, 0.13636364,
         0.13636364, 0.04545455, 0.04545455])),
 ((5, 0, 0),
  1): ([(4, 0, 1),
   (5, 0, 0),
   (5, 0, 1),
   (2, 0, 1),
   (3, 0, 1),
   (3, 0, 0),
   (2, 0, 0),
   (4,
    0,
    0)], array([0.05660377, 0.20754717, 0.28301887, 0.0754717 , 0.13207547,
         0.13207547, 0.03773585, 0.0754717 ])),
 ((2, 0, 2),
  1): ([(4, 0, 3),
   (2, 0, 3),
   (1, 0, 2),
   (2, 0, 2),
   (0, 0, 3),
   (3, 0, 3),
   (1, 0, 3),
   (3, 0, 2),
   (0,
    0,
    2)], array([0.05769231, 0.15384615, 0.09615385, 0.13461538, 0.09615385,
         0.19230769, 0.09615385, 0.15384615, 0.01923077])),
 ((1, 0, 1),
  2): ([(0, 0, 1),
   (0, 0, 2),
   (3, 0, 1),
   (2, 0, 2),
   (2, 0, 1),
   (1, 0, 2),
   (1, 0, 1),
   (3,
    0,
    2)], array([0.13461538, 0.13461538, 0.05769231, 0.32692308, 0.11538462,
         0.07692308, 0.13461538, 0.01923077])),
 ((3, 0, 3), 2): ([(4, 0, 3), (1, 0, 3), (3, 0, 3), (2, 0, 3), (5, 0, 3)],
  array([0.23333333, 0.36666667, 0.26666667, 0.1       , 0.03333333])),
 ((0, 0, 0),
  0): ([(2, 0, 0),
   (1, 0, 0),
   (0, 0, 1),
   (3, 0, 0),
   (0, 0, 0),
   (2, 0, 1),
   (1, 0, 1),
   (3,
    0,
    1)], array([0.12307692, 0.2       , 0.07692308, 0.09230769, 0.13846154,
         0.2       , 0.07692308, 0.09230769])),
 ((1, 0, 1),
  1): ([(2, 0, 1),
   (1, 0, 2),
   (0, 0, 2),
   (3, 0, 1),
   (2, 0, 2),
   (0, 0, 1),
   (1,
    0,
    1)], array([0.23076923, 0.17307692, 0.13461538, 0.13461538, 0.11538462,
         0.13461538, 0.07692308])),
 ((2, 0, 2),
  4): ([(0, 0, 2),
   (2, 0, 3),
   (0, 0, 3),
   (3, 0, 2),
   (1, 0, 2),
   (1, 0, 3),
   (3, 0, 3),
   (2, 0, 2),
   (4, 0, 2),
   (4, 0, 3),
   (5,
    0,
    2)], array([0.02702703, 0.08108108, 0.10810811, 0.16216216, 0.10810811,
         0.13513514, 0.10810811, 0.16216216, 0.02702703, 0.05405405,
         0.02702703])),
 ((0, 0, 2),
  2): ([(0, 0, 3),
   (1, 0, 2),
   (0, 0, 2),
   (2, 0, 3),
   (2, 0, 2),
   (1, 0, 3),
   (3,
    0,
    2)], array([0.27272727, 0.13636364, 0.22727273, 0.09090909, 0.04545455,

## 5) Compute inclusive values and CCS $\Delta EV (s ; j,0)$

Under logit, the $\textbf{ex-ante value}$ at a state is
$$V(s) = \gamma_E - \ln P(0 \mid s)$$
So we can $\textbf{simulate forward}$ using $\hat{P}$ and $\hat{p}$, summing discounted $\textbf{inclusive values}$, instead of solving Bellman.

In [277]:
states=list(ccp.keys())

def delta_ev_ccs(s,j):
    def path_val(start_s, initial_j):
        vals=[]
        for _ in range(DRAWS):
            s_current=draw_next_state(start_s, initial_j)
            acc=(BETA**1)*inclusive_value_from_ccp(ccp.get(s_current, np.ones(J)/J))
            for h in range(2,H+1):
                P_current=ccp.get(s_current, None)
                if P_current is None:
                    j_draw=0
                else:
                    j_draw=int(np.random.choice(J, p=P_current))
                s_current=draw_next_state(s_current, j_draw)
                acc+=(BETA**h)*inclusive_value_from_ccp(ccp.get(s_current, np.ones(J)/J))
            vals.append(acc)
        return float(np.mean(vals)) if vals else 0.0
    return path_val(s,j) - path_val(s,0)

delta_cache={}
for s in states:
    for j in range(1,J):
        delta_cache[(s,j)] = delta_ev_ccs(s,j)

len(delta_cache)

96

In [278]:
delta_cache

{((3, 0, 0), 1): -0.043460835355764615,
 ((3, 0, 0), 2): -0.019165669951242137,
 ((3, 0, 0), 3): -0.07760684320885414,
 ((3, 0, 0), 4): -0.05098050060588921,
 ((4, 0, 0), 1): -0.07334522985148251,
 ((4, 0, 0), 2): -0.19684043421785447,
 ((4, 0, 0), 3): -0.07043311907061778,
 ((4, 0, 0), 4): -0.1693905374888045,
 ((4, 0, 1), 1): -0.004307097541615512,
 ((4, 0, 1), 2): 0.11430835897070057,
 ((4, 0, 1), 3): 0.021095902086298857,
 ((4, 0, 1), 4): 0.12295829026950322,
 ((3, 0, 1), 1): 0.09009326847233812,
 ((3, 0, 1), 2): 0.17566395751295172,
 ((3, 0, 1), 3): 0.10765610587310714,
 ((3, 0, 1), 4): -0.029875380864122114,
 ((1, 0, 2), 1): 0.2901843347544997,
 ((1, 0, 2), 2): -0.05414312817212341,
 ((1, 0, 2), 3): 0.32242521424374093,
 ((1, 0, 2), 4): 0.13958487072592796,
 ((2, 0, 2), 1): 0.09630019484766894,
 ((2, 0, 2), 2): 0.0667556901071169,
 ((2, 0, 2), 3): 0.15993054679578922,
 ((2, 0, 2), 4): 0.03358498679285571,
 ((3, 0, 3), 1): 0.21431700078838078,
 ((3, 0, 3), 2): 0.21233985047055004,
 ((3, 0, 3), 3): 0.3364464121689079,
 ((3, 0, 3), 4): 0.22644347074277693,
 ((5, 0, 0), 1): -0.11122061282801177,
 ((5, 0, 0), 2): -0.029958530678767303,
 ((5, 0, 0), 3): -0.0791296397167196,
 ((5, 0, 0), 4): -0.07843831039311322,
 ((5, 0, 1), 1): 0.05158190790949835,
 ((5, 0, 1), 2): 0.06627689636952905,
 ((5, 0, 1), 3): 0.026293675471916522,
 ((5, 0, 1), 4): -0.09433592103806543,
 ((5, 0, 2), 1): -0.14161996980364933,
 ((5, 0, 2), 2): 0.13194795711557017,
 ((5, 0, 2), 3): -0.009855352599807077,
 ((5, 0, 2), 4): -0.06869096111321404,
 ((5, 0, 3), 1): 0.08061174729555942,
 ((5, 0, 3), 2): -0.0639294453446575,
 ((5, 0, 3), 3): 0.14780419890681173,
 ((5, 0, 3), 4): 0.16607091024697018,
 ((4, 0, 2), 1): 0.039547575054534434,
 ((4, 0, 2), 2): 0.017575347336975078,
 ((4, 0, 2), 3): -0.01822043773770865,
 ((4, 0, 2), 4): 0.06057156116927853,
 ((4, 0, 3), 1): 0.2524890541788385,
 ((4, 0, 3), 2): 0.27735626574231453,
 ((4, 0, 3), 3): 0.175463099896489,
 ((4, 0, 3), 4): 0.17121787732227833,
 ((0, 0, 0), 1): 0.026724534050852178,
 ((0, 0, 0), 2): -0.013460647517466562,
 ((0, 0, 0), 3): 0.06711452353191039,
 ((0, 0, 0), 4): -0.023627822858826697,
 ((1, 0, 1), 1): 0.02586182256970382,
 ((1, 0, 1), 2): 0.0712856534746713,
 ((1, 0, 1), 3): 0.07340459789640885,
 ((1, 0, 1), 4): 0.016177702779037517,
 ((2, 0, 1), 1): -0.0811309254423298,
 ((2, 0, 1), 2): 0.11625920268079248,
 ((2, 0, 1), 3): 0.04870545317309638,
 ((2, 0, 1), 4): 0.03498744848785762,
 ((2, 0, 0), 1): 0.05280747159877652,
 ((2, 0, 0), 2): 0.013597711397707712,
 ((2, 0, 0), 3): 0.14137190545310485,
 ((2, 0, 0), 4): 0.017074666080263867,
 ((0, 0, 1), 1): -0.13241337774439899,
 ((0, 0, 1), 2): 0.1969338738521662,
 ((0, 0, 1), 3): 0.002280709679506998,
 ((0, 0, 1), 4): -0.04194070205347522,
 ((0, 0, 3), 1): 0.32612247990420684,
 ((0, 0, 3), 2): 0.3067626975774562,
 ((0, 0, 3), 3): 0.5437121192148986,
 ((0, 0, 3), 4): 0.34071062809206243,
 ((1, 0, 3), 1): -0.021435078873646596,
 ((1, 0, 3), 2): 0.2925528617338644,
 ((1, 0, 3), 3): 0.32808322150237057,
 ((1, 0, 3), 4): 0.2739534236210197,
 ((3, 0, 2), 1): 0.19018403711395138,
 ((3, 0, 2), 2): 0.10408697827828384,
 ((3, 0, 2), 3): 0.15543532115256742,
 ((3, 0, 2), 4): 0.12570698856234053,
 ((2, 0, 3), 1): 0.09627121023888119,
 ((2, 0, 3), 2): 0.2662937535590624,
 ((2, 0, 3), 3): 0.3011974586263282,
 ((2, 0, 3), 4): 0.10057117961285211,
 ((1, 0, 0), 1): -0.059540363363905335,
 ((1, 0, 0), 2): -0.005388998509937792,
 ((1, 0, 0), 3): -0.11774498628378982,
 ((1, 0, 0), 4): -0.04588160954791132,
 ((0, 0, 2), 1): 0.35354883253859715,
 ((0, 0, 2), 2): 0.2963398880404222,
 ((0, 0, 2), 3): 0.04243174575774589,
 ((0, 0, 2), 4): 0.26129346104359463}

## 6) Minimum-distance (MD) fit of cost parameters

The HM moment says \textbf{empirical log-odds} must equal $(- \text{expected cost}) + \beta \times \text{CCS difference}.$

With latent types $L$, expected cost is $\textbf{mixture-weighted}$: $\sum_L \pi_L \big(k_0 + k_L + \varphi_L a \big).$

In [279]:
a_mids = np.array([0.5*(a_cuts[b]+a_cuts[b+1]) for b in range(len(a_cuts)-1)], float)

def objective(theta):
    k0, kL_low, kL_high, phi_low, phi_high, pi_low = theta
    pi=np.array([pi_low, max(1e-6, 1.0-pi_low)]); pi=pi/np.sum(pi)
    loss=0.0; wsum=0.0
    for s in states:
        ia,iy,iage = s
        P = ccp[s]
        a_mid = a_mids[ia]
        costs = np.array([k0 + kL_low + phi_low*a_mid, k0 + kL_high + phi_high*a_mid])
        exp_cost = float(np.sum(pi * costs))
        for j in range(1,J):
            logodds = float(np.log(P[j]) - np.log(P[0]))
            lam = -exp_cost + BETA * delta_cache[(s,j)]
            w = max(state_counts.get(s,1.0), 1.0)
            loss += (logodds - lam)**2 * w
            wsum += w
    return loss / max(wsum,1.0)

theta0 = np.array([20.0, 20.0, 5.0, 0.01, 0.005, 0.5], float)
rng = np.random.default_rng(0)
best_theta = theta0.copy(); best_val = objective(best_theta)
for it in range(200):
    cand = best_theta + rng.normal(0, [2,2,2,0.001,0.001,0.05], size=6)
    val = objective(cand)
    if val < best_val:
        best_theta, best_val = cand, val
best_val, best_theta

(141.49322126033553,
 array([ 6.49109223e+00,  3.30331823e+01,  3.33099195e+00, -7.69926920e-04,
         1.06379242e-04,  5.57136395e-01]))

## 7) EM: infer laten literacy (personal level)

The HM moment says \textbf{empirical log-odds} must equal $(- \text{expected cost}) + \beta \times \text{CCS difference}.$

With latent types $L$, expected cost is $\textbf{mixture-weighted}$: $\sum_L \pi_L \big(k_0 + k_L + \varphi_L a \big).$

In [280]:
def type_ccp(theta):
    k0, kL_low, kL_high, phi_low, phi_high, pi_low = theta
    def ccps_at_state(s, L):
        ia,_,_ = s
        a_mid = a_mids[ia]
        if L==0:
            kL, phi = kL_low, phi_low
        else:
            kL, phi = kL_high, phi_high
        lam = np.zeros(J); lam[0]=0.0
        for j in range(1,J):
            lam[j] = - (k0 + kL + phi*a_mid) + BETA * delta_cache[(s,j)]
        return softmax(lam)
    return ccps_at_state

traj = defaultdict(list)
for _, row in dfb.sort_values(['id','t']).iterrows():
    s_t = (int(row['ia']), int(row['iy']), int(row['iage']))
    j_t = int(row['j'])
    traj[int(row['id'])].append((s_t, j_t))

def em(theta_init, n_iter=2):
    theta = theta_init.copy()
    k0, kL_low, kL_high, phi_low, phi_high, pi_low = theta
    pi = np.array([pi_low, max(1e-6, 1.0-pi_low)]); pi = pi/np.sum(pi)
    for it in range(n_iter):
        ccps = type_ccp(theta)
        omega={}
        for pid, seq in traj.items():
            like=np.zeros(2)
            for L in [0,1]:
                ll=0.0
                for (s_t, j_t) in seq:
                    P = ccps(s_t, L)
                    ll += np.log(max(P[j_t], 1e-12))
                like[L]=np.exp(ll)
            post = pi * like
            s = post.sum()
            omega[pid] = post/s if s>0 else np.array([0.5,0.5])
        # update pi
        mat = np.stack(list(omega.values()))
        pi = mat.mean(axis=0); pi = pi/np.sum(pi)
        # small local search to re-fit costs keeping pi fixed
        def objective_fixed_pi(th):
            th = th.copy()
            th[-1] = pi[0]
            return objective(th)
        best = theta.copy(); best[-1] = pi[0]
        best_val = objective(best)
        for _ in range(100):
            cand = best + np.random.normal(0, [1,1,1,0.0005,0.0005,0.0], size=6)
            val = objective_fixed_pi(cand)
            if val < best_val:
                best, best_val = cand, val
        theta = best; theta[-1] = pi[0]
    return theta, pi, omega

theta_em, pi_em, omega = em(best_theta, n_iter=2)
theta_em, pi_em

(array([-6.31965809e+00,  3.18973951e+01,  3.75729348e+00,  3.14992746e-03,
        -1.20846153e-04,  4.00000001e-02]),
 array([0.04, 0.96]))

In [281]:
rows=[]
for pid, post in omega.items():
    rows.append({'id':pid, 'p_low': float(post[0]), 'p_high': float(post[1])})
post_df = pd.DataFrame(rows).sort_values('id').reset_index(drop=True)
post_df.head()

   id         p_low  p_high
0   1  8.498416e-57     1.0
1   2  4.145641e-80     1.0
2   3  7.557323e-10     1.0
3   4  1.011179e-56     1.0
4   5  4.764394e-80     1.0

In [282]:
post_df

      id         p_low  p_high
0      1  8.498416e-57     1.0
1      2  4.145641e-80     1.0
2      3  7.557323e-10     1.0
3      4  1.011179e-56     1.0
4      5  4.764394e-80     1.0
..   ...           ...     ...
595  596  3.176742e-33     1.0
596  597  1.721093e-56     1.0
597  598  1.507663e-56     1.0
598  599  1.512853e-56     1.0
599  600  1.148944e-56     1.0

[600 rows x 3 columns]

In [283]:
summary = {
    'theta_em': list(map(float, theta_em)),
    'pi_em': list(map(float, pi_em)),
    'objective_value': float(objective(theta_em))
}
print(json.dumps(summary, indent=2))

{
  "theta_em": [
    -6.319658092355856,
    31.89739513018396,
    3.757293477564619,
    0.00314992746326427,
    -0.00012084615289409864,
    0.040000000081243
  ],
  "pi_em": [
    0.040000000081243,
    0.9599999999187571
  ],
  "objective_value": 1.1079708024843702
}